export const SHA256 = /^[a-f0-9]{64}$/u;
export const GIT_OID = /^[a-f0-9]{40}$/u;
export const PRODUCT_IDS = [
  "8f3cc90d-56dd-4c1c-b9c2-0a1100500101",
  "952431be-51b8-42a2-9bf6-769a15934e85",
];
export const PROFILE_NAMES = ["inquiry-only", "matter-full"];
export const PROFILE_CONTRACTS = {
  [PRODUCT_IDS[0]]: {
    profile: "matter-full",
    mailbox_min_version: "1.14",
    production_manifest: "apps/addin/manifest.production.xml",
    taskpane_html: "index.html",
    required_static_paths: ["event-runtime.html", "event-runtime.js", "index.html"],
  },
  [PRODUCT_IDS[1]]: {
    profile: "inquiry-only",
    mailbox_min_version: "1.3",
    production_manifest: "apps/addin/manifest.inquiry.production.xml",
    taskpane_html: "outlook-addin/index.html",
    required_static_paths: ["outlook-addin/index.html"],
  },
};
export const EMPTY_ASSIGNMENT_FINGERPRINT_SHA256 = "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945";
export const ROLLBACK_ASSIGNMENT_RESTORE_POLICY = "reconcile_to_validated_single_visible_distribution";
export const PRODUCTION_DISTRIBUTION = Object.freeze({
  eligible_user_count: 10,
  excluded_user_count: 0,
  assignment_authority: "entra_object_id_allowlist",
  nested_groups_allowed: false,
  tenant_wide_assignment_allowed: false,
  assign_to_everyone: false,
  max_visible_addins_per_user: 1,
  assignment_overlap_count: 0,
  profiles: Object.freeze([
    Object.freeze({
      profile: "matter-full",
      product_id: PRODUCT_IDS[0],
      distribution_role: "production_visible",
      assignment_state: "assigned",
      production_user_visible: true,
      real_host_evidence_required: true,
      central_operation_type: "central_manifest_update",
    }),
    Object.freeze({
      profile: "inquiry-only",
      product_id: PRODUCT_IDS[1],
      distribution_role: "retained_unassigned",
      assignment_state: "unassigned",
      production_user_visible: false,
      real_host_evidence_required: false,
      central_operation_type: "central_manifest_update_and_unassign",
    }),
  ]),
});
export const MANIFEST_PATHS = [
  "apps/addin/manifest.inquiry.production.xml",
  "apps/addin/manifest.inquiry.xml",
  "apps/addin/manifest.production.xml",
  "apps/addin/manifest.xml",
];
export const CLIENT_GRAPH_SCOPES = ["Calendars.ReadWrite", "Mail.Read", "offline_access"];
// Keep the OAuth scope sequence byte-for-byte aligned with the delegated OAuth
// client. The authorization URL and token exchange serialize this array in
// order; sorting here would hide a contract drift even when the set is equal.
export const CLIENT_OAUTH_SCOPES = ["openid", "profile", "email", "offline_access", "Calendars.ReadWrite", "Mail.Read"];
// SHA-256 of the public, exact CLIENT_GRAPH_SCOPES/CLIENT_OAUTH_SCOPES contract.
// Scope equality is enforced before this receipt value is emitted.
export const CLIENT_SCOPE_FINGERPRINT_SHA256 = "e6cd56223945b881a0ac1b3775d216c612881343c2352fbe27d210c6b55b925d";
export const APPROVED_LICENSES = [
  "0BSD", "Apache-2.0", "BlueOak-1.0.0", "BSD-2-Clause", "BSD-3-Clause", "CC-BY-4.0", "ISC", "MIT",
  "(MIT AND Zlib)", "(MIT OR GPL-3.0-or-later)",
];
export const LICENSE_METADATA_OVERRIDES = Object.freeze({
  "node_modules/passport-strategy": Object.freeze({
    name: "passport-strategy",
    version: "1.0.0",
    integrity: "sha512-CB97UUvDKJde2V0KDWWB3lyf6PC3FaZP7YxZ2G8OAtn9p4HI9j9JLP9qjOGZFvyl8uwNT8qM+hGnz/n16NI7oA==",
    resolved: "https://registry.npmjs.org/passport-strategy/-/passport-strategy-1.0.0.tgz",
    license: "MIT",
  }),
});
export const REQUIRED_HOSTS = ["classic-outlook-windows", "new-outlook-windows", "outlook-macos", "owa"];
export const REQUIRED_COMMON_HOST_SCENARIOS = ["auth-reconnect", "item-switch", "offline-recovery"];
export const REQUIRED_PREREQUISITES = [
  "additive_migrations",
  "api_release",
  "approved_template_runtime",
  "docusign_endpoint_and_secret_reference",
  "graph_endpoint_and_secret_reference",
  "precedent_index_runtime",
  "static_release",
];
export const MUTATION_ACTIONS = Object.freeze({
  additive_migrations: "additive_migration_apply",
  api_release: "api_lambda_code_deploy",
  central_deployment: "m365_central_single_visible_transition",
  docusign_endpoint_and_secret_reference: "docusign_endpoint_secret_config",
  graph_endpoint_and_secret_reference: "graph_endpoint_secret_config",
  static_release: "static_dual_namespace_publish",
});
export const REQUIRED_MUTATION_ACTIONS = Object.freeze(Object.values(MUTATION_ACTIONS));
export const M365_DESKTOP_INSTALLATION_PROOF_SCHEMA =
  "amic-os.m365-desktop-installation-aggregate-proof.v1";
export const M365_DESKTOP_INSTALLATION_PROOF_CLASS = "desktop_installation";
export const REQUIRED_PROOF_CLASSES = [
  ...REQUIRED_PREREQUISITES,
  "authorization",
  "assignment_safety",
  "central_deployment",
  "go_live_approval",
  "monitoring_plan",
  "pilot_assignment",
  "desktop_installation",
  "propagation_observation",
  "real_outlook_host",
  "rollback_rehearsal",
  "rollback_static_inventory",
];
export const REQUIRED_RELEASE_PATHS = [
  "apps/addin/src/addin-auth.js",
  "apps/addin/src/inquiry-entry.jsx",
  "apps/addin/src/main.jsx",
  "apps/addin/src/matter-entry.js",
  "apps/addin/src/outlook-attachment-actions.js",
  "apps/addin/src/outlook-auth-runtime.js",
  "apps/addin/src/outlook-compact-shell.jsx",
  "apps/addin/src/outlook-connection-actions.js",
  "apps/addin/src/outlook-conversation-policy-feature.jsx",
  "apps/addin/src/outlook-conversation-policy-panel.jsx",
  "apps/addin/src/outlook-conversation-policy.js",
  "apps/addin/src/outlook-document-signing-feature.jsx",
  "apps/addin/src/outlook-document-signing-panel.jsx",
  "apps/addin/src/outlook-document-signing.js",
  "apps/addin/src/outlook-editable-action-state.js",
  "apps/addin/src/outlook-feature-catalog.js",
  "apps/addin/src/outlook-filing-correction-panel.jsx",
  "apps/addin/src/outlook-filing-correction.js",
  "apps/addin/src/outlook-filing-orchestration.js",
  "apps/addin/src/outlook-filing.js",
  "apps/addin/src/outlook-inquiry-actions.js",
  "apps/addin/src/outlook-inquiry-shell.jsx",
  "apps/addin/src/outlook-matter-shell.jsx",
  "apps/addin/src/outlook-overlay-state.js",
  "apps/addin/src/outlook-precedent-panel.jsx",
  "apps/addin/src/outlook-precedent-search.js",
  "apps/addin/src/outlook-profile-bootstrap.js",
  "apps/addin/src/outlook-session-fence.js",
  "apps/addin/src/outlook-surface-profile.js",
  "apps/addin/src/outlook-task-datetime.js",
  "apps/addin/src/styles.css",
  "apps/addin/public/amic-law-logo.svg",
  "apps/api/src/json-postgres-program-admin-lambda.js",
  "apps/api/src/outlook-addin-runtime-context.js",
  "apps/api/src/matter-runtime-context.js",
  "apps/api/src/matter-runtime-replay.js",
  "apps/api/src/microsoft-delegated-oauth-client.js",
  "apps/api/src/outlook-conversation-current-authority.js",
  "apps/api/src/outlook-conversation-operational-runtime.js",
  "apps/api/src/outlook-conversation-policy-api.js",
  "apps/api/src/outlook-document-api.js",
  "apps/api/src/outlook-graph-webhook.js",
  "apps/api/src/outlook-time-entry-draft-adapter.js",
  "apps/api/src/server.js",
  "apps/api/src/vault-dms-runtime-context.js",
  "apps/web/src/App.jsx",
  "apps/web/src/components/VaultSurface.jsx",
  "apps/web/src/data/apiClient.js",
  "packages/dms/src/search/precedent-common.js",
  "packages/dms/src/search/precedent-search-repository.js",
  "packages/dms/src/search/postgres-precedent-repository.js",
  "packages/email-dms/src/email-filing-correction-service.js",
  "packages/email-dms/src/m365-connection-model.js",
  "packages/email-dms/src/postgres-conversation-policy-service.js",
  "packages/email-dms/src/postgres-conversation-sync-store.js",
  "packages/email-dms/src/postgres-graph-subscription-service.js",
  "packages/integrations-core/src/docusign-envelope-adapter.js",
  "packages/integrations-core/src/docusign-postgres-repository.js",
  "packages/matter/src/approved-document-builder-service.js",
  "packages/matter/src/document-approval-service.js",
  "packages/matter/src/document-publication-reconciliation.js",
  "packages/matter/src/document-publication-service.js",
  "packages/matter/src/outlook-task-adapter.js",
  "scripts/lib/upl-proof-runner.mjs",
  "scripts/lib/outlook-release/m365-distribution.mjs",
  "scripts/run-upl-c09-c12-outlook-addin-browser-proof.mjs",
  "scripts/validate-upl-c09-c12-outlook-addin.mjs",
];
export const REQUIRED_TEST_PATHS = [
  "apps/addin/test/addin-auth.test.js",
  "apps/addin/test/manifest-profiles.test.js",
  "apps/addin/test/manifest-runtime.test.js",
  "apps/addin/test/outlook-attachment-actions.test.js",
  "apps/addin/test/outlook-attachment-boundary.test.js",
  "apps/addin/test/outlook-auth-runtime.test.js",
  "apps/addin/test/outlook-connection-actions.test.js",
  "apps/addin/test/outlook-conversation-document-main-browser.test.js",
  "apps/addin/test/outlook-conversation-policy-feature.test.js",
  "apps/addin/test/outlook-conversation-policy-outm28.test.js",
  "apps/addin/test/outlook-document-signing-feature.test.js",
  "apps/addin/test/outlook-document-signing-panel.test.js",
  "apps/addin/test/outlook-document-signing.test.js",
  "apps/addin/test/outlook-editable-action-state.test.js",
  "apps/addin/test/outlook-editable-actions-browser.test.js",
  "apps/addin/test/outlook-feature-catalog-evaluation.test.js",
  "apps/addin/test/outlook-feature-catalog.test.js",
  "apps/addin/test/outlook-filing-correction-end-to-end.test.js",
  "apps/addin/test/outlook-filing-correction-main-browser.test.js",
  "apps/addin/test/outlook-filing-correction-panel.test.js",
  "apps/addin/test/outlook-filing-correction.test.js",
  "apps/addin/test/outlook-filing-orchestration.test.js",
  "apps/addin/test/outlook-filing-zero-trust.test.js",
  "apps/addin/test/outlook-filing.test.js",
  "apps/addin/test/outlook-inquiry-entry.test.js",
  "apps/addin/test/outlook-main-filing-wiring.test.js",
  "apps/addin/test/outlook-main-matter-context-wiring.test.js",
  "apps/addin/test/outlook-main-session-isolation-browser.test.js",
  "apps/addin/test/outlook-main-session-isolation-lifecycle-browser.test.js",
  "apps/addin/test/outlook-main-session-isolation-lifecycle-office-storage-browser.test.js",
  "apps/addin/test/outlook-main-session-isolation-owner.test.js",
  "apps/addin/test/outlook-main-session-isolation.test.js",
  "apps/addin/test/outlook-matter-rail.test.js",
  "apps/addin/test/outlook-overlay-state.test.js",
  "apps/addin/test/outlook-precedent-main-browser.test.js",
  "apps/addin/test/outlook-precedent-panel.test.js",
  "apps/addin/test/outlook-precedent-search.test.js",
  "apps/addin/test/outlook-profile-build-artifact.mjs",
  "apps/addin/test/outlook-shell-contract.test.js",
  "apps/addin/test/outlook-shell-responsive.test.js",
  "apps/addin/test/outlook-task-datetime.test.js",
  "apps/addin/test/outlook-ui-contract.test.js",
  "apps/addin/test/profile-bootstrap.test.js",
  "apps/api/test/json-postgres-program-admin-lambda.test.js",
  "apps/api/test/microsoft-delegated-oauth-client.test.js",
  "apps/api/test/cmp-r4-g5-vault.test.js",
  "apps/api/test/outlook-addin-api.test.js",
  "apps/api/test/outlook-conversation-authority-loss-maintenance.test.js",
  "apps/api/test/outlook-conversation-authority-loss.test.js",
  "apps/api/test/outlook-conversation-canonical-message.test.js",
  "apps/api/test/outlook-conversation-policy-api.test.js",
  "apps/api/test/outlook-conversation-policy-status-api.test.js",
  "apps/api/test/outlook-document-api.test.js",
  "apps/api/test/outlook-graph-webhook.test.js",
  "apps/api/test/outlook-time-entry-draft-postgres.test.js",
  "apps/api/test/outlook-email-filing-correction-response-binding.test.js",
  "apps/api/test/outlook-inquiry-registration-service.test.js",
  "apps/api/test/outlook-precedent-api.test.js",
  "apps/api/test/outm32-approval-publication-replay-api.test.js",
  "apps/api/test/outm32-document-builder-api.test.js",
  "apps/api/test/outm32-generic-actor-replay-api.test.js",
  "apps/web/test/search-preferences.test.mjs",
  "packages/dms/test/postgres-precedent-lifecycle.test.js",
  "packages/dms/test/postgres-precedent-search.test.js",
  "packages/email-dms/test/conversation-policy.test.js",
  "packages/email-dms/test/email-filing-correction-concurrency.test.js",
  "packages/email-dms/test/graph-notification-queue.test.js",
  "packages/email-dms/test/conversation-sync-migration.test.js",
  "packages/email-dms/test/postgres-conversation-sync-store.test.js",
  "packages/email-dms/test/postgres-conversation-policy-service.test.js",
  "packages/integrations-core/test/docusign-concurrency.test.js",
  "packages/integrations-core/test/docusign-outm33-34-hardening.test.js",
  "packages/integrations-core/test/docusign-postgres-concurrency.test.js",
  "packages/matter/test/document-builder-approval.test.js",
  "packages/matter/test/document-builder-docx.test.js",
  "packages/matter/test/document-builder-postgres-reconciliation.test.js",
  "packages/matter/test/document-builder-publication.test.js",
  "packages/matter/test/outlook-task-adapter.test.js",
  "scripts/test/outlook-release-candidate.test.mjs",
  "scripts/test/outlook-release-cli-workflow.test.mjs",
  "scripts/test/outlook-release-gates.test.mjs",
  "scripts/test/outlook-release-profile-artifacts.test.mjs",
];
export const REQUIRED_STATIC_PATHS = [
  "amic-law-icon.png", "amic-law-logo.svg", "event-runtime.html", "event-runtime.js", "index.html",
  "oauth-callback.html", "oauth-callback.js", "oauth-start.html", "oauth-start.js",
  "outlook-addin/index.html",
];
export const FORBIDDEN_BUILD_SUFFIXES = [".key", ".map", ".p12", ".pem", ".pfx"];
export const FORBIDDEN_BUILD_TEXT = [
  "-----BEGIN PRIVATE KEY-----", "-----BEGIN RSA PRIVATE KEY-----", "/Users/",
  "/home/runner/work/", "sourcesContent\"",
];
export const STATIC_NAMESPACES = [
  { excluded_source_prefixes: ["outlook-addin/"], invalidation_path: "/addin/*", product_id: PRODUCT_IDS[0], profile: "matter-full", source_prefix: "", target_prefix: "addin/" },
  { excluded_source_prefixes: [], invalidation_path: "/outlook-addin/*", product_id: PRODUCT_IDS[1], profile: "inquiry-only", source_prefix: "outlook-addin/", target_prefix: "outlook-addin/" },
];
export const CANDIDATE_ALLOWED_CLAIM = "Exact source, deterministic local build, four official manifest validations, frozen profile drift, rollback metadata, and dependency licenses passed.";
export const CANDIDATE_BLOCKED_CLAIM = "This receipt is not API/static/M365 deployment, propagation, real Outlook host, Graph delivery, DocuSign sandbox, or go-live evidence.";
