const BOUNDARY = "payroll/PayrollBoundaryPanel.tsx";
const STATEMENTS = "payroll/PayrollStatementWorkspace.tsx";
const ATTENDANCE = "attendance/AttendanceWorkspace.tsx";
const PAY_RULES = "payroll/PayRulesWorkspace.tsx";
const PAY_CATALOG = "payroll/PayrollCatalogWorkspace.tsx";

function capability({
  capability_id,
  area,
  method,
  path,
  route_policy_id,
  client_function = null,
  ui_surfaces = [],
  classification = "reuse",
  follow_up_unit = null,
  provider_kind = null,
}) {
  return Object.freeze({
    capability_id,
    area,
    method,
    path,
    route_policy_id,
    client_function,
    ui_surfaces: Object.freeze([...ui_surfaces]),
    classification,
    follow_up_unit,
    provider_kind,
    production_ready_claim: false,
  });
}

export const PAYROLL_CAPABILITY_LEDGER = Object.freeze([
  capability({ capability_id: "legacy.preview", area: "호환 미리보기", method: "POST", path: "/api/hrx/payroll/preview", route_policy_id: "hrx.payroll.preview", client_function: "createHrxPayrollPreview" }),
  capability({ capability_id: "legacy.approve", area: "호환 승인", method: "POST", path: "/api/hrx/payroll/approve", route_policy_id: "hrx.payroll.approve", client_function: "approveHrxPayrollPreview" }),
  capability({ capability_id: "legacy.export", area: "호환 내보내기", method: "POST", path: "/api/hrx/payroll/export", route_policy_id: "hrx.payroll.export", client_function: "exportHrxPayrollArtifact" }),

  capability({ capability_id: "items.list", area: "급여 항목", method: "GET", path: "/api/hrx/payroll/items", route_policy_id: "hrx.payroll.items.read", client_function: "fetchHrxPayrollItems", ui_surfaces: [PAY_CATALOG], follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "items.create", area: "급여 항목", method: "POST", path: "/api/hrx/payroll/items", route_policy_id: "hrx.payroll.items.create", client_function: "createHrxPayrollItem", ui_surfaces: [PAY_CATALOG], follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "items.update", area: "급여 항목", method: "PATCH", path: "/api/hrx/payroll/items/item-a", route_policy_id: "hrx.payroll.items.update", client_function: "updateHrxPayrollItem", ui_surfaces: [PAY_CATALOG], follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "profile.self", area: "내 급여정보", method: "GET", path: "/api/hrx/payroll/me/profile", route_policy_id: "hrx.payroll.self.read", client_function: "fetchHrxPayrollSelfProfile", classification: "ui_gap", follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "profile.read", area: "구성원 급여정보", method: "GET", path: "/api/hrx/payroll/profiles/employee-a", route_policy_id: "hrx.payroll.profiles.read", client_function: "fetchHrxPayrollProfile", ui_surfaces: [PAY_CATALOG], follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "profile.create", area: "구성원 급여정보", method: "POST", path: "/api/hrx/payroll/profiles", route_policy_id: "hrx.payroll.profiles.create", client_function: "createHrxPayrollProfile", ui_surfaces: [PAY_CATALOG], follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "profile.update", area: "구성원 급여정보", method: "PATCH", path: "/api/hrx/payroll/profiles/profile-a", route_policy_id: "hrx.payroll.profiles.update", client_function: "updateHrxPayrollProfile", ui_surfaces: [PAY_CATALOG], follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "assignment.create", area: "급여 항목 배정", method: "POST", path: "/api/hrx/payroll/profiles/profile-a/assignments", route_policy_id: "hrx.payroll.assignment.create", client_function: "assignHrxPayrollItem", ui_surfaces: [PAY_CATALOG], follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "assignment.retire", area: "급여 항목 배정", method: "POST", path: "/api/hrx/payroll/profiles/profile-a/assignments/assignment-a/retire", route_policy_id: "hrx.payroll.assignment.retire", client_function: "retireHrxPayrollItemAssignment", ui_surfaces: [PAY_CATALOG], follow_up_unit: "PEO-TUW-064" }),
  capability({ capability_id: "attendance.approve", area: "근태 급여 인계", method: "POST", path: "/api/hrx/payroll/attendance-approvals", route_policy_id: "hrx.payroll.attendance.approve", client_function: "approveHrxPayrollAttendance", ui_surfaces: [ATTENDANCE] }),

  capability({ capability_id: "dashboard.summary", area: "급여 집계", method: "GET", path: "/api/hrx/payroll/dashboard-summary", route_policy_id: "hrx.payroll.runtime.read", client_function: "fetchHrxPayrollDashboardSummary" }),
  capability({ capability_id: "period.list", area: "급여기간", method: "GET", path: "/api/hrx/payroll/periods", route_policy_id: "hrx.payroll.runtime.read", client_function: "fetchHrxPayrollWorkspace", ui_surfaces: [BOUNDARY, STATEMENTS] }),
  capability({ capability_id: "period.create", area: "급여기간", method: "POST", path: "/api/hrx/payroll/periods", route_policy_id: "hrx.payroll.runtime.prepare", client_function: "createHrxPayrollPeriod", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "run.create", area: "정산차수", method: "POST", path: "/api/hrx/payroll/runs", route_policy_id: "hrx.payroll.runtime.prepare", client_function: "createHrxPayrollRun", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "run.adjustment.create", area: "정정 정산", method: "POST", path: "/api/hrx/payroll/runs", route_policy_id: "hrx.payroll.runtime.prepare", client_function: "createHrxPayrollAdjustmentRun", ui_surfaces: [BOUNDARY], follow_up_unit: "PEO-TUW-063" }),
  capability({ capability_id: "run.read", area: "정산차수", method: "GET", path: "/api/hrx/payroll/runs/run-a", route_policy_id: "hrx.payroll.runtime.read", client_function: "fetchHrxPayrollRun", ui_surfaces: [BOUNDARY, STATEMENTS] }),
  capability({ capability_id: "run.precheck", area: "마감 전 확인", method: "GET", path: "/api/hrx/payroll/runs/run-a/precheck", route_policy_id: "hrx.payroll.runtime.read", client_function: "fetchHrxPayrollClosePrecheck", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "run.snapshot", area: "입력 확정", method: "POST", path: "/api/hrx/payroll/runs/run-a/snapshot", route_policy_id: "hrx.payroll.runtime.prepare", client_function: "captureHrxPayrollRun", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "run.preview", area: "급여 계산", method: "POST", path: "/api/hrx/payroll/runs/run-a/preview", route_policy_id: "hrx.payroll.runtime.prepare", client_function: "previewHrxPayrollRun", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "issue.resolve", area: "이슈 확인", method: "POST", path: "/api/hrx/payroll/issues/issue-a/resolve", route_policy_id: "hrx.payroll.runtime.review", client_function: "resolveHrxPayrollIssue", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "run.approve", area: "급여 승인", method: "POST", path: "/api/hrx/payroll/runs/run-a/approve", route_policy_id: "hrx.payroll.runtime.approve", client_function: "approveHrxPayrollRun", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "run.close", area: "급여 마감", method: "POST", path: "/api/hrx/payroll/runs/run-a/close", route_policy_id: "hrx.payroll.runtime.approve", client_function: "closeHrxPayrollRun", ui_surfaces: [BOUNDARY] }),

  capability({ capability_id: "allowance_rule.list", area: "수당 기준", method: "GET", path: "/api/hrx/payroll/rules", route_policy_id: "hrx.payroll.runtime.read", client_function: "fetchHrxPayrollAllowanceRules", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-065,PEO-TUW-067" }),
  capability({ capability_id: "allowance_rule.create", area: "수당 기준", method: "POST", path: "/api/hrx/payroll/rules", route_policy_id: "hrx.payroll.runtime.prepare", client_function: "createHrxPayrollAllowanceRule", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-065,PEO-TUW-067" }),
  capability({ capability_id: "allowance_rule.review", area: "수당 기준 검토", method: "POST", path: "/api/hrx/payroll/rules/rule-a/review", route_policy_id: "hrx.payroll.runtime.review", client_function: "reviewHrxPayrollAllowanceRule", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-065,PEO-TUW-067" }),
  capability({ capability_id: "allowance_rule.publish", area: "수당 기준 적용", method: "POST", path: "/api/hrx/payroll/rules/rule-a/publish", route_policy_id: "hrx.payroll.runtime.approve", client_function: "publishHrxPayrollAllowanceRule", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-065,PEO-TUW-067" }),
  capability({ capability_id: "minimum_wage.list", area: "최저임금 기준", method: "GET", path: "/api/hrx/payroll/minimum-wage", route_policy_id: "hrx.payroll.runtime.read", client_function: "fetchHrxMinimumWageStandards", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-066,PEO-TUW-067" }),
  capability({ capability_id: "minimum_wage.create", area: "최저임금 기준", method: "POST", path: "/api/hrx/payroll/minimum-wage", route_policy_id: "hrx.payroll.runtime.prepare", client_function: "createHrxMinimumWageStandard", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-066,PEO-TUW-067" }),
  capability({ capability_id: "minimum_wage.legal_approve", area: "최저임금 법률 검토 승인", method: "POST", path: "/api/hrx/payroll/minimum-wage/rule-a/legal-approve", route_policy_id: "hrx.payroll.minimum_wage.legal_review", client_function: "legallyApproveHrxMinimumWageStandard", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-067" }),
  capability({ capability_id: "minimum_wage.review", area: "최저임금 기준 검토", method: "POST", path: "/api/hrx/payroll/minimum-wage/rule-a/review", route_policy_id: "hrx.payroll.runtime.review", client_function: "reviewHrxMinimumWageStandard", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-066,PEO-TUW-067" }),
  capability({ capability_id: "minimum_wage.publish", area: "최저임금 기준 적용", method: "POST", path: "/api/hrx/payroll/minimum-wage/rule-a/publish", route_policy_id: "hrx.payroll.runtime.approve", client_function: "publishHrxMinimumWageStandard", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-066,PEO-TUW-067" }),
  capability({ capability_id: "minimum_wage.preview", area: "최저임금 영향 확인", method: "POST", path: "/api/hrx/payroll/minimum-wage/preview", route_policy_id: "hrx.payroll.runtime.prepare", client_function: "previewHrxMinimumWageImpact", ui_surfaces: [PAY_RULES], follow_up_unit: "PEO-TUW-066,PEO-TUW-067" }),

  capability({ capability_id: "statement.list", area: "급여명세서", method: "GET", path: "/api/hrx/payroll/runs/run-a/statements", route_policy_id: "hrx.payroll.statement.manage.read", client_function: "fetchHrxPayrollStatements", ui_surfaces: [STATEMENTS] }),
  capability({ capability_id: "statement.generate", area: "급여명세서", method: "POST", path: "/api/hrx/payroll/runs/run-a/statements/generate", route_policy_id: "hrx.payroll.statement.manage.write", client_function: "generateHrxPayrollStatements", ui_surfaces: [STATEMENTS] }),
  capability({ capability_id: "statement.deliver", area: "급여명세서 전달", method: "POST", path: "/api/hrx/payroll/runs/run-a/statements/deliver", route_policy_id: "hrx.payroll.statement.manage.write", client_function: "deliverHrxPayrollStatements", ui_surfaces: [STATEMENTS], classification: "provider_missing", follow_up_unit: "PEO-TUW-068,PEO-TUW-070", provider_kind: "delivery" }),
  capability({ capability_id: "statement.provider_callback", area: "급여명세서 전달 결과 수신", method: "POST", path: "/api/hrx/payroll/provider-callbacks/statement-delivery", route_policy_id: "hrx.payroll.statement.provider_callback", classification: "provider_missing", follow_up_unit: "PEO-TUW-068,PEO-TUW-070", provider_kind: "delivery" }),
  capability({ capability_id: "statement.export", area: "급여대장", method: "GET", path: "/api/hrx/payroll/runs/run-a/export", route_policy_id: "hrx.payroll.statement.export", client_function: "exportHrxPayrollRegister", ui_surfaces: [STATEMENTS] }),
  capability({ capability_id: "statement.self.list", area: "내 급여명세서", method: "GET", path: "/api/hrx/payroll/statements/self", route_policy_id: "hrx.payroll.statement.self.read", client_function: "fetchHrxPayrollStatementsSelf", ui_surfaces: [STATEMENTS] }),
  capability({ capability_id: "statement.self.download", area: "내 급여명세서", method: "GET", path: "/api/hrx/payroll/statements/statement-a/download", route_policy_id: "hrx.payroll.statement.self.read", client_function: "readHrxPayrollStatement", ui_surfaces: [STATEMENTS] }),
  capability({ capability_id: "statement.revoke", area: "급여명세서 철회", method: "POST", path: "/api/hrx/payroll/statements/statement-a/revoke", route_policy_id: "hrx.payroll.statement.manage.write", client_function: "revokeHrxPayrollStatement", ui_surfaces: [STATEMENTS], follow_up_unit: "PEO-TUW-070" }),

  capability({ capability_id: "payment.prepare", area: "급여 지급", method: "POST", path: "/api/hrx/payroll/runs/run-a/payments/prepare", route_policy_id: "hrx.payroll.payment.prepare", client_function: "prepareHrxPayrollPayment", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "payment.read", area: "급여 지급", method: "GET", path: "/api/hrx/payroll/payment-batches/batch-a", route_policy_id: "hrx.payroll.payment.read", client_function: "fetchHrxPayrollPayment" }),
  capability({ capability_id: "payment.approve", area: "급여 지급", method: "POST", path: "/api/hrx/payroll/payment-batches/batch-a/approve", route_policy_id: "hrx.payroll.payment.approve", client_function: "approveHrxPayrollPayment", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "payment.export", area: "은행 지급 파일", method: "POST", path: "/api/hrx/payroll/payment-batches/batch-a/export", route_policy_id: "hrx.payroll.payment.prepare", client_function: "exportHrxPayrollPayment", ui_surfaces: [BOUNDARY], classification: "provider_missing", follow_up_unit: "PEO-TUW-068,PEO-TUW-069", provider_kind: "bank" }),
  capability({ capability_id: "payment.reconcile", area: "지급 결과 확인", method: "POST", path: "/api/hrx/payroll/payment-batches/batch-a/reconcile", route_policy_id: "hrx.payroll.payment.prepare", client_function: "reconcileHrxPayrollPayment", ui_surfaces: [BOUNDARY], classification: "provider_missing", follow_up_unit: "PEO-TUW-068,PEO-TUW-069", provider_kind: "bank" }),
  capability({ capability_id: "payment.retry_failed", area: "실패 건 재처리", method: "POST", path: "/api/hrx/payroll/payment-batches/batch-a/retry-failed", route_policy_id: "hrx.payroll.payment.prepare", client_function: "retryFailedHrxPayrollPayment", ui_surfaces: [BOUNDARY], classification: "provider_missing", follow_up_unit: "PEO-TUW-069", provider_kind: "bank" }),

  capability({ capability_id: "filing.list", area: "급여 신고", method: "GET", path: "/api/hrx/payroll/runs/run-a/filings", route_policy_id: "hrx.payroll.filing.read", client_function: "fetchHrxPayrollFilings" }),
  capability({ capability_id: "filing.create", area: "급여 신고", method: "POST", path: "/api/hrx/payroll/runs/run-a/filings", route_policy_id: "hrx.payroll.filing.prepare", client_function: "createHrxPayrollFiling", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "filing.validate", area: "급여 신고", method: "POST", path: "/api/hrx/payroll/filings/filing-a/validate", route_policy_id: "hrx.payroll.filing.prepare", client_function: "validateHrxPayrollFiling", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "filing.submit", area: "급여 신고", method: "POST", path: "/api/hrx/payroll/filings/filing-a/submit", route_policy_id: "hrx.payroll.filing.submit", client_function: "submitHrxPayrollFiling", ui_surfaces: [BOUNDARY], classification: "provider_missing", follow_up_unit: "PEO-TUW-068,PEO-TUW-069", provider_kind: "filing" }),
  capability({ capability_id: "filing.correct", area: "급여 신고", method: "POST", path: "/api/hrx/payroll/filings/filing-a/correct", route_policy_id: "hrx.payroll.filing.prepare", client_function: "correctHrxPayrollFiling", ui_surfaces: [BOUNDARY] }),

  capability({ capability_id: "year_end.collect", area: "연말정산", method: "POST", path: "/api/hrx/payroll/runs/run-a/year-end/collect", route_policy_id: "hrx.payroll.year_end.prepare", client_function: "collectHrxPayrollYearEnd", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "year_end.calculate", area: "연말정산", method: "POST", path: "/api/hrx/payroll/runs/run-a/year-end/calculate", route_policy_id: "hrx.payroll.year_end.prepare", client_function: "calculateHrxPayrollYearEnd", ui_surfaces: [BOUNDARY] }),
  capability({ capability_id: "year_end.review", area: "연말정산", method: "POST", path: "/api/hrx/payroll/runs/run-a/year-end/review", route_policy_id: "hrx.payroll.year_end.review", client_function: "reviewHrxPayrollYearEnd", ui_surfaces: [BOUNDARY] }),
]);

export const PAYROLL_INFRASTRUCTURE_INVENTORY = Object.freeze({
  attribution: "global_extracted_inventory",
  migration_ids: Object.freeze([
    "021_hrx_payroll_runtime",
    "022_hrx_payroll_inputs",
    "023_hrx_payroll_profile_units",
    "024_hrx_payroll_run_controls",
    "025_hrx_payroll_year_end",
    "026_hrx_payroll_catalog_assignments",
    "027_hrx_attendance_approval_receipts",
    "039_hrx_payroll_adjustment_keys",
    "040_hrx_payroll_provider_states",
    "042_hrx_payroll_statement_provider_events",
    "043_hrx_minimum_wage_legal_review",
    "044_hrx_payroll_provider_attempts",
    "046_hrx_payment_reconciliation_staging",
    "047_hrx_payroll_filing_corrections",
  ]),
  schema_identifiers: Object.freeze([
    "hrx_attendance_approval_receipts",
    "hrx_attendance_records",
    "hrx_compensation_records",
    "hrx_employees",
    "hrx_overtime_requests",
    "hrx_payroll_adjustments",
    "hrx_payroll_delivery_receipts",
    "hrx_payroll_employee_results",
    "hrx_payroll_filing_jobs",
    "hrx_payroll_input_snapshots",
    "hrx_payroll_issues",
    "hrx_payroll_item_assignments",
    "hrx_payroll_items",
    "hrx_payroll_line_items",
    "hrx_payroll_outbox",
    "hrx_payroll_payment_batches",
    "hrx_payroll_payment_items",
    "hrx_payroll_periods",
    "hrx_payroll_profiles",
    "hrx_payroll_provider_operations",
    "hrx_payroll_rule_versions",
    "hrx_payroll_runs",
    "hrx_payroll_statement_provider_events",
    "hrx_payroll_statement_templates",
    "hrx_payroll_statements",
    "hrx_payroll_year_end_cases",
  ]),
  provider_ports: Object.freeze([
    "accountResolver",
    "bankAdapter",
    "bankReconciliationPort",
    "deliveryPort",
    "filingProviderPort",
    "minimumWageInputResolver",
    "payrollStatementProviderVerifier",
  ]),
  production_ready_claim: false,
});

export const PAYROLL_CAPABILITY_AUDIT = Object.freeze({
  schema_version: "PEO-TUW-060.v3",
  production_ready_claim: false,
  authority_dimensions: Object.freeze([
    "server_route_policy",
    "web_client_export",
    "reachable_people_surface",
    "hrx_migration_schema",
    "provider_port",
  ]),
  classification_values: Object.freeze(["reuse", "ui_gap", "domain_defect", "provider_missing", "evidence_missing"]),
  evidence_missing: Object.freeze([
    "macos_package_hash",
    "windows_package_hash",
    "package_qa_ref",
    "owner_approval_ref",
    "legal_signoff_ref",
    "labor_signoff_ref",
    "tax_signoff_ref",
    "delivery_production_receipt",
    "bank_production_receipt",
    "filing_production_receipt",
    "go_live_approval_ref",
  ]),
});
