export const concurrentUsersScenario = {
  id: "PERF-SCENARIO-03",
  name: "concurrent_users_mixed_workflow",
  dry_run_only: true,
  runtime_requests_executed: false,
  required_counts: {
    users: 10,
    matters: 10,
    documents: 10,
    emails: 10,
    tasks: 10,
    issues: 10
  },
  measures: ["simulated_users", "workflow_step_count", "error_rate"],
  boundary: "Synthetic mixed workflow plan only; no staging traffic is generated by dry-run."
};
