import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";
import { startOutlookAddinStaticServer } from "../../../scripts/lib/outlook-addin-static-server.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const DIST = path.join(ROOT, "apps/addin/dist");
const A = "matter-a", B = "matter-b";
const json = (body, status = 200) => ({ status, contentType: "application/json; charset=utf-8", body: JSON.stringify(body) });
const item = (key) => ({ itemId: `office-${key}`, subject: `메일 ${key}`, internetMessageId: `<${key}@example.invalid>`, conversationId: `conversation-${key}`, from: { displayName: "Sender", emailAddress: "sender@example.invalid" }, to: [], attachments: [], body: { getAsync(_type, cb) { cb({ status: "succeeded", value: `body-${key}` }); } }, getAllInternetHeadersAsync(cb) { cb({ status: "succeeded", value: "Date: Mon, 10 Aug 2026 00:00:00 +0000" }); } });
const matter = (id) => ({ matter_id: id, matter_code: id.toUpperCase(), title: `Matter ${id.toUpperCase()}`, client_display_name: `Client ${id.toUpperCase()}`, status: "open" });
const timeline = (id) => ({ request_id: `timeline-${id}`, outcome: "passed", item: { matter_id: id, visible_entries: [{ matter_id: id, event_id: `event-${id}`, type: "outlook.email.filed", title: `Timeline ${id.toUpperCase()}`, occurred_at: "2026-08-10T00:00:00.000Z", source_ref: `thread-${id}` }], page_info: { limit: 8, has_more: false, next_cursor: null } } });
const receipt = (id, ref = "invalid-until-runtime") => ({ item_context_ref: ref, matter_id: id, operation: "file_email", outcome: "created", email_thread_id: `receipt-${id}`, completed_at: "2026-08-10T00:00:00.000Z" });
const tokenFor = (value) => `lawos_session_v1.${value}`;
const fnv1a64 = (value) => { let hash = 0xcbf29ce484222325n; for (const character of value) { hash ^= BigInt(character.codePointAt(0)); hash = BigInt.asUintN(64, hash * 0x100000001b3n); } return hash.toString(16).padStart(16, "0"); };
const itemContextRef = (currentItem, canonical) => `item-context:${fnv1a64(`${currentItem.rest_message_id}\u001f${currentItem.internet_message_id}\u001f${currentItem.conversation_id}\u001eread\u001freceived\u001f${canonical}`)}`;

async function openFixture(browser, { authLoss = false, itemChange = false, holdStorage = false, editable = false, overlap = false } = {}) {
  const state = { holds: new Map(), release: {}, phase: authLoss ? "old" : "normal", itemChange, editable, overlap, overlapPrimed: false, requests: [], tokens: new Map() };
  const page = await browser.newPage({ viewport: { width: 420, height: 800 } });
  await page.addInitScript(({ a, b, initialToken }) => {
    const items = { A: a, B: b }, handlers = [], mailbox = { item: items.A, userProfile: { emailAddress: "qa@example.invalid" }, addHandlerAsync(_t, h) { handlers.push(h); }, removeHandlerAsync(_t, { handler } = {}) { const i = handlers.indexOf(handler); if (i >= 0) handlers.splice(i, 1); } };
    let bridgeMessageHandler = null; let officeToken = initialToken; const pendingRemoves = [];
    window.Office = { onReady: (cb) => cb({ host: "Outlook", platform: "web" }), EventType: { ItemChanged: "itemChanged" }, actions: { associate() {} }, MailboxEnums: { RestVersion: { v2_0: "v2.0" }, CoercionType: { Text: "text" } }, context: { requirements: { isSetSupported: (name, version) => name === "NestedAppAuth" && version === "1.1" }, mailbox } };
    let tokenCalls = 0; window.__NAA_METHODS = []; window.__NAA_REQUESTS = []; window.nestedAppAuthBridge = { addEventListener(_type, handler) { bridgeMessageHandler = handler; }, postMessage(raw) { const request = JSON.parse(raw); window.__NAA_METHODS.push(request.method); window.__NAA_REQUESTS.push(request); const response = request.method === "GetInitContext" ? { requestId: request.requestId, success: true, initContext: { sdkName: "browser-test", sdkVersion: "1.0.0", accountContext: null, capabilities: {} } } : (++tokenCalls === 1 ? { requestId: request.requestId, success: false, error: { code: "interaction_required", message: "interactive login required" } } : { requestId: request.requestId, success: true, token: { access_token: "entra-B", id_token: "eyJhbGciOiJub25lIn0.eyJvaWQiOiJicm93c2VyLUIiLCJ0aWQiOiJicm93c2VyLXRlbmFudCIsInByZWZlcnJlZF91c2VybmFtZSI6InFhQGV4YW1wbGUuaW52YWxpZCIsIm5hbWUiOiJCIn0.signature", expires_in: 3600, scope: "api://browser-client/access_as_user", authority: "https://login.microsoftonline.com/organizations" }, account: { homeAccountId: "browser-B.browser-tenant", username: "qa@example.invalid", tenantId: "browser-tenant", localAccountId: "browser-B", environment: "login.microsoftonline.com" } }); queueMicrotask(() => bridgeMessageHandler?.({ data: JSON.stringify(response) })); } };
    mailbox.convertToRestId = (id) => id.replace("office-", "rest-"); window.__STORAGE_REMOVE_STARTED = false; window.__STORAGE_REMOVE_PENDING = 0; window.__STORAGE_REMOVE_QUEUED = 0; window.__RELEASE_STORAGE_REMOVE = () => { while (pendingRemoves.length) pendingRemoves.shift()(); }; window.OfficeRuntime = { storage: { getItem: async () => officeToken, setItem: async (_key, value) => { officeToken = value; }, removeItem: async () => { window.__STORAGE_REMOVE_STARTED = true; window.__STORAGE_REMOVE_PENDING += 1; if (window.__HOLD_STORAGE_REMOVE) await new Promise((resolve) => { window.__STORAGE_REMOVE_QUEUED += 1; pendingRemoves.push(() => { window.__STORAGE_REMOVE_QUEUED -= 1; resolve(); }); }); window.__STORAGE_REMOVE_PENDING -= 1; officeToken = null; } } }; window.__SET_OFFICE_TOKEN = (value) => { officeToken = value; }; window.__HOLD_STORAGE_REMOVE = false; window.sessionStorage.setItem("lawos_addin_session_token", initialToken);
    window.__SET_ITEM = (key) => { mailbox.item = items[key]; handlers.slice().forEach((handler) => handler()); };
  }, { a: item("A"), b: item("B"), initialToken: overlap ? tokenFor("A") : tokenFor("browser-test") });
  await page.evaluate((hold) => { window.__HOLD_STORAGE_REMOVE = hold; }, holdStorage);
  await page.route("https://appsforoffice.microsoft.com/**", (r) => r.fulfill(json("")));
  await page.route("**/api/**", async (route) => {
    const req = route.request(), url = new URL(req.url()), method = req.method(), auth = req.headers().authorization ?? "", caller = auth.endsWith(".B") ? "B" : auth.endsWith(".A") ? "A" : "normal"; state.requests.push(`${caller}:${url.pathname}`); state.tokens.set(url.pathname, caller);
    const fulfill = (body, status = 200) => route.fulfill(json(body, status));
    const wait = (key) => new Promise((resolve) => { const queue = state.holds.get(key) ?? []; queue.push(resolve); state.holds.set(key, queue); state.release[key] = (body, status = 200, contentType = "application/json; charset=utf-8", raw = false) => { (state.holds.get(key) ?? []).splice(0).forEach((done) => done({ body, status, contentType, raw })); state.holds.delete(key); }; }).then(({ body, status, contentType, raw }) => route.fulfill({ status, contentType, body: raw ? body : JSON.stringify(body) }));
    if (url.pathname === "/api/auth/office-sso/config") return fulfill({ item: { configured: true, client_id: "browser-client", tenant_id: "organizations", api_scope: "api://browser-client/access_as_user", scopes: ["api://browser-client/access_as_user"], callback_uri: `${url.origin}/addin/oauth-callback.html`, authority: "https://login.microsoftonline.com/organizations" } });
    if (url.pathname === "/api/auth/session") return fulfill({ authenticated: true, principal: { user_id: caller === "B" ? "browser-user-b" : "browser-user", tenant_id: "browser-tenant" } });
    if (url.pathname === "/api/auth/office-sso/exchange") return fulfill({ session_token: tokenFor("B") });
    if (url.pathname === "/api/outlook/connection") return fulfill({ item: { status: "connected", active: true, connection_id: "m365_connection_session_qa", state_version: 1, mailbox_address: "qa@example.invalid" } });
    if (url.pathname === "/api/outlook/bootstrap") return authLoss && state.phase === "old" ? wait("bootstrap") : fulfill({ item: { ready: true, marker: caller === "B" ? "current-b" : state.phase } });
    if (url.pathname === "/api/outlook/matters") {
      if (url.searchParams.has("q")) { const query = url.searchParams.get("q"); if (authLoss && state.phase === "old" && query === "stale") return wait("search"); if (overlap && state.overlapPrimed && caller === "A" && query === "late-bodyless") return wait("overlap-search"); if (overlap && state.overlapPrimed && caller === "A" && query === "late-json") return wait("overlap-json"); return fulfill({ items: [matter(caller === "B" || state.phase === "new" ? B : A)] }); }
      const id = url.searchParams.get("matter_id"); return fulfill({ items: [matter(id || B)] });
    }
    if (url.pathname === "/api/outlook/messages/identity") return fulfill({ item: { canonical_graph_message_id: `canonical-${state.phase}`, rest_message_id: req.postDataJSON()?.rest_message_id, internet_message_id: req.postDataJSON()?.internet_message_id, conversation_id: req.postDataJSON()?.conversation_id } });
    if (url.pathname === "/api/outlook/operation-receipts/readback") { if (authLoss && state.phase === "old") return wait("receipt"); if (overlap && state.overlapPrimed && caller === "A") return wait("overlap-receipt"); const post = req.postDataJSON?.() ?? {}; const current = post.current_item ?? {}; return fulfill({ items: [receipt(B, itemContextRef(current, `canonical-${state.phase}`))] }); }
    if (url.pathname.endsWith("/timeline")) { if (authLoss && state.phase === "old") return route.fulfill({ status: 401, contentType: "text/plain; charset=utf-8", body: "" }); if (overlap && state.overlapPrimed && caller === "A") return route.fulfill({ status: 401, contentType: "text/plain; charset=utf-8", body: "" }); if (itemChange && state.phase === "normal") return wait("timeline"); return fulfill(timeline(caller === "B" || state.phase === "new" ? B : A)); }
    if (url.pathname.endsWith("/documents")) { if (authLoss && state.phase === "old") return route.fulfill({ status: 401, contentType: "text/html; charset=utf-8", body: "<html>expired</html>" }); if (overlap && state.overlapPrimed && caller === "A") return wait("overlap-documents"); if (itemChange && state.phase === "normal") return wait("documents"); return fulfill({ items: [{ document_id: `doc-${caller === "B" ? "current" : state.phase}`, title: `Document ${caller === "B" ? "CURRENT" : state.phase.toUpperCase()}` }] }); }
    if (state.editable && url.pathname === "/api/outlook/tasks" && method === "POST") { const body = { request_id: `task-${state.phase}`, outcome: "task_created", item: { activity_id: `task-${state.phase}`, version: 1, title: req.postDataJSON()?.task?.title ?? "" } }; return state.phase === "normal" ? wait("task") : fulfill(body); }
    if (state.editable && url.pathname === "/api/outlook/time-entry-drafts" && method === "POST") { const body = { request_id: `time-${state.phase}`, outcome: "time_entry_draft_created", item: { draft_ref: `time-${state.phase}`, version: 1 } }; return state.phase === "normal" ? wait("time") : fulfill(body); }
    return fulfill({ items: [] });
  });
  const web = await startOutlookAddinStaticServer({ distRoot: DIST });
  await page.goto(`${web.origin}/addin/`, { waitUntil: "domcontentloaded" });
  await page.waitForSelector(".outlook-compact-shell"); await page.waitForFunction(() => document.querySelector("[data-feature-id='matter.search']")?.disabled === false);
  await page.waitForFunction(() => document.querySelector("[data-feature-id='matter.search']")?.disabled === false);
  return { page, state, web };
}

async function searchAndSelect(page, id) {
  await page.locator("[data-feature-id='matter.search']").click(); await page.locator("#matter-search-input").fill(id); await page.waitForTimeout(320); await page.locator("#matter-select").selectOption(id === "stale" ? A : id); await page.waitForTimeout(50);
}

test("main business reads do not cross an auth generation and a fresh generation applies", async () => {
  const browser = await chromium.launch({ headless: true }); const { page, state, web } = await openFixture(browser, { authLoss: true, holdStorage: true });
  try {
    await page.locator("[data-feature-id='matter.search']").click(); await page.locator("#matter-search-input").fill("stale"); await page.waitForTimeout(320); state.release.search?.({ items: [matter(A)] }); await page.waitForTimeout(100); await page.locator("#matter-select").selectOption(A); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" }); await page.locator("[data-feature-id='matter.search']").click(); await page.locator("#matter-search-input").fill("stale"); await page.waitForTimeout(320); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" }); await page.locator("[data-feature-id='all-functions']").click(); await page.locator("[data-action-row='matter-readbacks'] button").click(); state.release.search?.({ items: [matter(A)] });
    state.release.receipt?.({ items: [receipt(A)] }); state.release.bootstrap?.({ item: { ready: true, marker: "old" } }); await page.waitForTimeout(80); assert.equal(await page.evaluate(() => window.__STORAGE_REMOVE_STARTED), true); assert.equal(await page.locator("[data-testid='business-gate']").count(), 1); assert.equal(await page.locator("[data-testid='outlook-overlay']").count(), 0); await page.evaluate(() => window.__RELEASE_STORAGE_REMOVE()); await page.waitForTimeout(80);
    assert.equal(await page.locator("[data-testid='business-gate']").count(), 1); assert.equal(await page.locator("[data-testid='outlook-overlay']").count(), 0); assert.doesNotMatch(await page.locator("body").innerText(), /MATTER-A|Timeline MATTER-A|Document OLD|receipt-A/u);
    state.phase = "new"; await page.reload({ waitUntil: "domcontentloaded" }); await page.waitForSelector("[data-feature-id='matter.search']"); await searchAndSelect(page, "matter-b"); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForTimeout(120);
    await page.locator("[data-feature-id='all-functions']").click(); await page.waitForFunction(() => document.querySelector("[data-testid='timeline-list']")?.innerText.includes("Timeline MATTER-B")); assert.match(await page.locator("body").innerText(), /Timeline MATTER-B|Document NEW/u);
  } finally { await page.close(); await browser.close(); await new Promise((resolve) => web.server.close(resolve)); }
});

test("late Item A readback success and error are suppressed after Item B changes", async () => {
  const browser = await chromium.launch({ headless: true }); const { page, state, web } = await openFixture(browser, { itemChange: true });
  try {
    await page.locator("[data-feature-id='matter.search']").click(); await page.locator("#matter-search-input").fill("matter-a"); await page.waitForTimeout(320); await page.locator("#matter-select").selectOption(A); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" }); await page.waitForTimeout(100); await page.locator("[data-feature-id='all-functions']").click(); await page.locator("[data-action-row='matter-readbacks'] button").click();
    await page.evaluate(() => window.__SET_ITEM("B")); state.release.timeline?.(timeline(A)); state.release.documents?.({ safe_error_code: "READBACK_FAILED" }, 500); await page.waitForTimeout(120); assert.doesNotMatch(await page.locator("body").innerText(), /MATTER-A|Timeline MATTER-A|Document NORMAL/u); assert.equal(await page.locator("[data-testid='outlook-overlay']").count(), 0);
  } finally { await page.close(); await browser.close(); await new Promise((resolve) => web.server.close(resolve)); }
});

test("late A unauthorized bodies cannot invalidate an interactive B session", async () => {
  const browser = await chromium.launch({ headless: true }); const { page, state, web } = await openFixture(browser, { overlap: true });
  const waitForHold = async (...keys) => { for (let i = 0; i < 50 && keys.some((key) => !state.holds.has(key)); i += 1) await page.waitForTimeout(20); if (keys.some((key) => !state.holds.has(key))) throw new Error(`expected held requests missing: ${keys.filter((key) => !state.holds.has(key)).join(",")}`); };
  try {
    await searchAndSelect(page, "matter-a"); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" }); state.overlapPrimed = true;
    await page.locator("[data-feature-id='matter.search']").click(); await page.locator("#matter-search-input").fill("late-bodyless"); await page.waitForTimeout(320); await page.locator("#matter-search-input").fill("late-json"); await waitForHold("overlap-search", "overlap-json"); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" });
    await page.locator("[data-feature-id='all-functions']").click(); await page.locator("[data-action-row='matter-readbacks'] button").click(); await waitForHold("overlap-documents"); await page.waitForTimeout(500); if (!(await page.locator("[data-testid='lawos-login-button']").count())) throw new Error(`A 401 did not expose login: ${state.requests.join(",")} naa=${await page.evaluate(() => window.__NAA_METHODS?.join(","))} body=${(await page.locator("body").innerText()).slice(0,400)}`);
    const exchange = page.waitForRequest((request) => request.url().endsWith("/api/auth/office-sso/exchange"), { timeout: 2_000 }); await page.locator("[data-testid='lawos-login-button']").click(); try { await exchange; } catch (error) { throw new Error(`interactive exchange missing: ${error.message}; body=${(await page.locator("body").innerText()).slice(0,400)}`); } await page.waitForFunction(() => sessionStorage.getItem("lawos_addin_session_token")?.endsWith(".B"));
    await searchAndSelect(page, "matter-b"); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" }); await page.locator("[data-feature-id='all-functions']").click(); await page.locator("[data-action-row='matter-readbacks'] button").click(); await page.waitForFunction(() => document.body.innerText.includes("Timeline MATTER-B")); await page.waitForSelector("[data-testid='busy-state']", { state: "detached" });
    const bReceiptReads = state.requests.filter((request) => request === "B:/api/outlook/operation-receipts/readback").length; assert.ok(bReceiptReads >= 1); assert.match(await page.locator("body").innerText(), /MATTER-B|Document CURRENT/u); assert.equal(await page.locator("[data-testid='busy-state']").count(), 0);
    const lateNaaCount = await page.evaluate(() => window.__NAA_METHODS?.length ?? 0); await page.evaluate(() => { window.__HOLD_STORAGE_REMOVE = true; window.__SET_OFFICE_TOKEN("lawos_session_v1.A"); }); state.release["overlap-search"]?.("", 401, "text/plain; charset=utf-8", true); state.release["overlap-json"]?.({ safe_error_code: "AUTH_SESSION_INVALID" }, 401); state.release["overlap-documents"]?.("<html>late-a</html>", 401, "text/html; charset=utf-8", true); await page.waitForTimeout(180);
    assert.equal(await page.evaluate(() => window.__NAA_METHODS?.length ?? 0), lateNaaCount);
    assert.equal(state.requests.filter((request) => request === "B:/api/outlook/operation-receipts/readback").length, bReceiptReads); assert.deepEqual(await page.evaluate(() => ({ token: sessionStorage.getItem("lawos_addin_session_token"), pending: window.__STORAGE_REMOVE_PENDING, queued: window.__STORAGE_REMOVE_QUEUED })), { token: "lawos_session_v1.B", pending: 0, queued: 0 }); assert.equal(await page.locator("[data-testid='business-gate']").count(), 0); assert.equal(await page.locator("[data-testid='lawos-login-button']").count(), 0); assert.equal(await page.locator("[data-testid='busy-state']").count(), 0); assert.match(await page.locator("body").innerText(), /MATTER-B|Timeline MATTER-B|Document CURRENT/u); assert.doesNotMatch(await page.locator("body").innerText(), /late-a|AUTH_SESSION_INVALID/u);
  } finally { await page.close(); await browser.close(); await new Promise((resolve) => web.server.close(resolve)); }
});

test("late task and time writes cannot populate an old auth-effect generation", async () => {
  const browser = await chromium.launch({ headless: true }); const { page, state, web } = await openFixture(browser, { editable: true });
  const restart = async () => { const session = page.waitForRequest((r) => r.url().endsWith("/api/auth/session")); await page.evaluate(() => window.dispatchEvent(new Event("lawos:office-ready"))); await session; await page.waitForTimeout(80); };
  try {
    await page.locator("[data-feature-id='matter.search']").click(); await page.locator("#matter-search-input").fill("matter-a"); await page.waitForTimeout(320); await page.locator("#matter-select").selectOption(A); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" });
    await page.locator("[data-feature-id='task.create']").click(); await page.locator("#task-draft-title").fill("OLD TASK"); const taskRequest = page.waitForRequest((r) => r.url().endsWith("/api/outlook/tasks") && r.method() === "POST"); await page.locator("[data-testid='create-task-button']").click(); await taskRequest; await restart(); state.release.task?.({ request_id: "task-old", outcome: "task_created", item: { activity_id: "task-old", version: 1, title: "OLD TASK" } }); await page.waitForTimeout(120); assert.doesNotMatch(await page.locator("body").innerText(), /task-old/u);
    if (await page.locator("[data-testid='outlook-overlay']").count()) { await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" }); }
    await page.locator("[data-feature-id='time-entry.draft']").click(); await page.locator("#time-entry-narrative").fill("OLD TIME"); const timeRequest = page.waitForRequest((r) => r.url().endsWith("/api/outlook/time-entry-drafts") && r.method() === "POST"); await page.locator("[data-testid='create-time-entry-draft-button']").click(); await timeRequest; await restart(); state.release.time?.({ request_id: "time-old", outcome: "time_entry_draft_created", item: { draft_ref: "time-old", version: 1 } }); await page.waitForTimeout(120); assert.doesNotMatch(await page.locator("body").innerText(), /OLD TIME|time-old/u);
    state.phase = "new"; await page.reload({ waitUntil: "domcontentloaded" }); await page.waitForSelector("[data-feature-id='matter.search']"); await searchAndSelect(page, "matter-b"); await page.locator("[data-testid='outlook-overlay-close']").click(); await page.waitForSelector("[data-testid='outlook-overlay']", { state: "detached" }); await page.locator("[data-feature-id='task.create']").click(); await page.locator("#task-draft-title").fill("CURRENT TASK"); await page.locator("[data-testid='create-task-button']").click(); await page.waitForFunction(() => document.body.innerText.includes("task-new")); assert.match(await page.locator("body").innerText(), /task-new/u);
  } finally { await page.close(); await browser.close(); await new Promise((resolve) => web.server.close(resolve)); }
});
