import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("packaged renderer presents user-facing connection login and feature checks", async () => {
  const source = await readFile(new URL("../src/renderer/offline.html", import.meta.url), "utf8");

  assert.match(source, /data-matter-desktop-app/);
  assert.match(source, /data-login-email/);
  assert.match(source, /data-login-password/);
  assert.match(source, /data-matter-login/);
  assert.match(source, /window\.matterSession/);
  assert.match(source, /data-auth-mode="sign_in"/);
  assert.match(source, /data-auth-mode-panel="reset_requested"/);
  assert.match(source, /data-auth-mode-panel="reset_confirm"/);
  assert.match(source, /data-auth-mode-panel="reset_success"/);
  assert.match(source, /data-launch-logo-flow/);
  assert.match(source, /brandLoginIntro/);
  assert.match(source, /brandLoginIntro 1900ms/);
  assert.match(source, /matterWordLoginReveal/);
  assert.match(source, /logo-handoff-active/);
  assert.match(source, /logoDockToHeader/);
  assert.match(source, /logoDockToHeader 1240ms/);
  assert.match(source, /appShellAfterLogoHandoff/);
  assert.match(source, /data-reset-token/);
  assert.match(source, /data-reset-new-password/);
  assert.match(source, /data-reset-confirm-password/);
  assert.match(source, /data-reset-confirm-submit/);
  assert.match(source, /data-resend-password-reset/);
  assert.match(source, /data-return-to-signin/);
  assert.match(source, /onPasswordResetDeepLink/);
  assert.match(source, /비밀번호가 설정되었습니다\. 새 비밀번호로 로그인하세요\./);
  assert.match(source, /등록 여부와 관계없이 같은 안내를 보여드립니다\./);
  assert.doesNotMatch(source, /data-account-select|재설정 토큰/);
  assert.match(source, /matter_vault_admin/);
  assert.match(source, /워크스페이스 연결됨/);
  assert.match(source, /Pretendard, SUIT/);
  assert.match(source, /로그인에 문제가 있나요\?/);
  assert.doesNotMatch(source, /Can't sign in/);
  assert.match(source, /기능 확인/);
  assert.doesNotMatch(source, /AWS temporary runtime connected|Function smoke|Dashboard smoke|Admin smoke|Runtime unavailable/);
  assert.doesNotMatch(source, /MATTER_VAULT_R4_OPERATOR_TOKEN/);
  assert.doesNotMatch(source, /operatorToken/);
  assert.doesNotMatch(source, /latestResetEmail/);
  assert.doesNotMatch(source, /reset_url|email_message|reset_token\s*[:=]/);
  assert.doesNotMatch(source, /localStorage|sessionStorage|indexedDB/);
});
