import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("packaged renderer presents user-facing connection login and feature checks", async () => {
  const source = await readFile(new URL("../src/renderer/offline.html", import.meta.url), "utf8");

  assert.match(source, /data-matter-desktop-app/);
  assert.match(source, /data-login-email/);
  assert.match(source, /data-login-password/);
  assert.match(source, /data-matter-login/);
  assert.match(source, /window\.matterSession/);
  assert.match(source, /data-auth-mode="sign_in"/);
  assert.match(source, /data-auth-mode-panel="reset_requested"/);
  assert.match(source, /data-auth-mode-panel="reset_confirm"/);
  assert.match(source, /data-auth-mode-panel="reset_success"/);
  assert.match(source, /data-launch-logo-flow/);
  assert.match(source, /data-logo-intro="pending"/);
  assert.match(source, /claimLogoIntro/);
  assert.match(source, /brandLoginIntro/);
  assert.match(source, /brandLoginIntro 1900ms/);
  assert.match(source, /--motion-press:\s*70ms/);
  assert.match(source, /--motion-hover:\s*110ms/);
  assert.match(source, /--motion-menu:\s*150ms/);
  assert.match(source, /--motion-content:\s*180ms/);
  assert.match(source, /--motion-panel:\s*240ms/);
  assert.match(source, /--ease-standard:\s*cubic-bezier\(0\.2, 0, 0\.38, 0\.9\)/);
  assert.match(source, /button:active/);
  assert.match(source, /button:focus-visible/);
  assert.match(source, /authPanelIn var\(--motion-content\) var\(--ease-out\) both/);
  assert.match(source, /prefers-reduced-motion: reduce/);
  assert.match(source, /transform: none !important/);
  assert.match(source, /matterWordLoginReveal/);
  assert.match(source, /body\[data-logo-intro="play"\] \.brand-lockup/);
  assert.doesNotMatch(source, /logo-handoff-active/);
  assert.doesNotMatch(source, /logoDockToHeader/);
  assert.doesNotMatch(source, /appShellAfterLogoHandoff/);
  assert.match(source, /data-reset-token/);
  assert.match(source, /data-reset-new-password/);
  assert.match(source, /data-reset-confirm-password/);
  assert.match(source, /data-reset-confirm-submit/);
  assert.match(source, /data-resend-password-reset/);
  assert.match(source, /data-return-to-signin/);
  assert.doesNotMatch(source, /skipNextLoginHandoffAnimation/);
  assert.doesNotMatch(source, /const handoffDelay = skipAnimation \? 0 : 1360/);
  assert.match(source, /web\/index\.html\?desktop=1&view=home&data=live&ctx=allow&splash=0/);
  assert.match(source, /function desktopApiBaseUrlForHandoff/);
  assert.match(source, /desktop_api_base_url/);
  assert.match(source, /\["127\.0\.0\.1", "localhost"\]\.includes\(url\.hostname\)/);
  assert.match(source, /productUiTarget\(session, \{ splash: false \}\)/);
  assert.match(source, /window\.setTimeout\(\(\) => \{[\s\S]*window\.location\.assign\(target\);[\s\S]*\}, 0\);/);
  assert.match(source, /function loginFailureMessage/);
  assert.match(source, /email_password_required/);
  assert.match(source, /password_reset_required/);
  assert.match(source, /auth_required/);
  assert.match(source, /이메일 또는 비밀번호가 맞지 않습니다/);
  assert.match(source, /event\.key !== "Enter"/);
  assert.match(source, /onPasswordResetDeepLink/);
  assert.match(source, /비밀번호가 설정되었습니다\. 새 비밀번호로 로그인하세요\./);
  assert.match(source, /등록 여부와 관계없이 같은 안내를 보여드립니다\./);
  assert.doesNotMatch(source, /data-account-select|재설정 토큰/);
  assert.match(source, /matter_vault_admin/);
  assert.match(source, /워크스페이스 연결됨/);
  assert.match(source, /Pretendard, SUIT/);
  assert.match(source, /로그인에 문제가 있나요\?/);
  assert.doesNotMatch(source, /Can't sign in/);
  assert.match(source, /기능 확인/);
  assert.doesNotMatch(source, /AWS temporary runtime connected|Function smoke|Dashboard smoke|Admin smoke|Runtime unavailable/);
  assert.doesNotMatch(source, /MATTER_VAULT_R4_OPERATOR_TOKEN/);
  assert.doesNotMatch(source, /operatorToken/);
  assert.doesNotMatch(source, /latestResetEmail/);
  assert.doesNotMatch(source, /reset_url|email_message|reset_token\s*[:=]/);
  assert.doesNotMatch(source, /localStorage|sessionStorage|indexedDB/);
});

test("desktop web renderer uses restrained SaaS motion tokens", async () => {
  const source = await readFile(new URL("../../web/src/motion.css", import.meta.url), "utf8");
  const entrypoint = await readFile(new URL("../../web/src/main.jsx", import.meta.url), "utf8");

  assert.match(entrypoint, /import "\.\/motion\.css"/);
  assert.match(source, /--ui-press:\s*70ms/);
  assert.match(source, /--ui-hover:\s*110ms/);
  assert.match(source, /--ui-menu:\s*150ms/);
  assert.match(source, /--ui-content:\s*180ms/);
  assert.match(source, /--ui-panel:\s*240ms/);
  assert.match(source, /--ui-pulse:\s*900ms/);
  assert.match(source, /--ease-standard:\s*cubic-bezier\(0\.2, 0, 0\.38, 0\.9\)/);
  assert.match(source, /button:active:not\(:disabled\)/);
  assert.match(source, /\.top-axis-item,[\s\S]*\.sidebar-item,[\s\S]*var\(--ui-menu\)/);
  assert.match(source, /\.sidebar-subnav[\s\S]*animation: ui-content-in var\(--ui-panel\) var\(--ease-out\) both/);
  assert.match(source, /\.surface,[\s\S]*\.builder-surface[\s\S]*animation: ui-content-in var\(--ui-content\) var\(--ease-out\) both/);
  assert.match(source, /\.live-data-loading[\s\S]*animation: ui-state-pulse var\(--ui-pulse\) var\(--ease-standard\) infinite alternate/);
  assert.match(source, /@media \(prefers-reduced-motion: reduce\)[\s\S]*transition-duration: 1ms !important/);
  assert.match(source, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.live-data-loading/);
});
