import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("packaged renderer presents user-facing connection login and feature checks", async () => {
  const source = await readFile(new URL("../src/renderer/offline.html", import.meta.url), "utf8");
  const introA = await readFile(new URL("../build/amic-law-a-lockup-accent.svg", import.meta.url), "utf8");
  const introMic = await readFile(new URL("../build/amic-law-mic-accent.svg", import.meta.url), "utf8");
  const finalLogo = await readFile(new URL("../build/amic-law-logo-accent.svg", import.meta.url), "utf8");

  assert.match(source, /data-matter-desktop-app/);
  assert.match(source, /data-login-skin="forest"/);
  assert.match(source, /data-login-screen="parnas-split"/);
  assert.match(source, /matter-login-stage/);
  assert.match(source, /matter-login-copy/);
  assert.match(source, /matter-login-form-column/);
  assert.match(source, /matter-login-photo-panel/);
  assert.match(source, /auth-forest-panel/);
  assert.match(source, /forest-login\.jpg/);
  assert.match(source, /data-brand-intro/);
  assert.match(source, /data-brand-intro-logo/);
  assert.match(source, /brand-intro-a/);
  assert.match(source, /brand-intro-mic/);
  assert.match(source, /brand-intro-logo/);
  assert.match(source, /amic-law-a-lockup-accent\.svg/);
  assert.match(source, /amic-law-mic-accent\.svg/);
  assert.match(source, /amic-law-logo-accent\.svg/);
  assert.match(source, /\.\.\/\.\.\/build\/icon\.png/);
  assert.doesNotMatch(source, /icon-source-mark\.png/);
  assert.doesNotMatch(source, /<img class="brand-intro-logo"/);
  assert.match(source, /aria-label="AMIC Law"/);
  assert.doesNotMatch(source, /amic-petra-main\.svg/);
  assert.match(introA, /fill="#26C260"/);
  assert.match(introMic, /fill="#26C260"/);
  assert.match(finalLogo, /fill="#26C260"/);
  assert.doesNotMatch(introMic, /M0 27\.708/);
  assert.doesNotMatch(introMic, /#0F3A32/);
  assert.doesNotMatch(finalLogo, /#0F3A32/);
  assert.match(source, /data-login-email/);
  assert.match(source, /data-login-password/);
  assert.match(source, /data-matter-login/);
  assert.match(source, /window\.matterSession/);
  assert.match(source, /data-auth-mode="sign_in"/);
  assert.match(source, /data-auth-mode-panel="reset_requested"/);
  assert.match(source, /data-auth-mode-panel="reset_confirm"/);
  assert.match(source, /data-auth-mode-panel="reset_success"/);
  assert.match(source, /data-launch-logo-flow/);
  assert.match(source, /data-logo-intro="pending"/);
  assert.match(source, /claimLogoIntro/);
  assert.match(source, /LOGO_INTRO_DURATION_MS = 3600/);
  assert.match(source, /setLogoIntroHandoffTarget/);
  assert.match(source, /logoIntroHandoffLocked/);
  assert.match(source, /setLogoIntroHandoffTarget\(\{ force: true \}\)/);
  assert.match(source, /getBoundingClientRect/);
  assert.match(source, /sourceCenterX = window\.innerWidth \/ 2/);
  assert.match(source, /introLogoParts/);
  assert.match(source, /--intro-logo-dx/);
  assert.match(source, /--intro-logo-dy/);
  assert.match(source, /--intro-logo-scale/);
  assert.match(source, /playLogoIntro/);
  assert.match(source, /completeLogoIntroAfterPlay/);
  assert.match(source, /amicLawLockupIntro/);
  assert.match(source, /amicLawAIntro/);
  assert.match(source, /--ease-brand-birth:\s*cubic-bezier\(0\.34, 0, 0\.12, 1\)/);
  assert.match(source, /--ease-brand-shift:\s*cubic-bezier\(0\.22, 0\.9, 0\.2, 1\)/);
  assert.match(source, /--ease-brand-reveal:\s*cubic-bezier\(0\.18, 0\.82, 0\.24, 1\)/);
  assert.match(source, /--ease-brand-dock:\s*cubic-bezier\(0\.16, 1, 0\.3, 1\)/);
  assert.match(source, /clip-path:\s*inset\(100% 22% 0 22%\)/);
  assert.match(source, /10% \{[\s\S]*opacity: 0\.74;[\s\S]*clip-path: inset\(52% 10% 0 10%\)/);
  assert.match(source, /17% \{[\s\S]*clip-path: inset\(0 0 0 0\)/);
  assert.match(source, /amicLawMicIntro/);
  assert.doesNotMatch(source, /amicLawWordmarkIntro/);
  assert.match(source, /amicLawIntroLayer 3200ms linear/);
  assert.match(source, /forestPhotoIn 520ms var\(--ease-brand-dock\) 2780ms/);
  assert.match(source, /forestLoginItemIn 360ms var\(--ease-brand-dock\)/);
  assert.match(source, /body\[data-login-skin="forest"\]\[data-logo-intro="play"\] \.matter-login-form-column \.matter-logo \{[\s\S]*opacity: 1;[\s\S]*transform: none;[\s\S]*animation: none;/);
  assert.doesNotMatch(source, /body\[data-login-skin="forest"\]\[data-logo-intro="play"\] \.matter-login-form-column \.matter-logo,\n\s*body\[data-login-skin="forest"\]\[data-logo-intro="play"\] \.matter-login-heading/);
  assert.match(source, /0%,\n\s*42% \{[\s\S]*translateX\(var\(--intro-a-origin-shift\)\)[\s\S]*animation-timing-function: var\(--ease-brand-shift\)/);
  assert.match(source, /47% \{[\s\S]*translate\(-50%, -50%\) translateX\(-3px\)/);
  assert.match(source, /49%,\n\s*82% \{[\s\S]*translate\(-50%, -50%\) translateX\(0\)[\s\S]*animation-timing-function: var\(--ease-brand-dock\)/);
  assert.match(source, /87%,\n\s*100% \{[\s\S]*--intro-logo-dx/);
  assert.match(source, /42% \{[\s\S]*clip-path: inset\(0 100% 0 0\)[\s\S]*animation-timing-function: var\(--ease-brand-reveal\)/);
  assert.match(source, /46% \{[\s\S]*opacity: 0\.86;[\s\S]*clip-path: inset\(0 24% 0 0\)/);
  assert.match(source, /body\[data-login-skin="forest"\]\[data-logo-intro="play"\] \.matter-login-heading \{[\s\S]*animation-delay: 2780ms/);
  assert.match(source, /body\[data-login-skin="forest"\]\[data-logo-intro="play"\] \.matter-login-field:nth-of-type\(1\) \{[\s\S]*animation-delay: 2780ms/);
  assert.match(source, /body\[data-login-skin="forest"\]\[data-logo-intro="play"\] \.matter-login-field:nth-of-type\(2\) \{[\s\S]*animation-delay: 2780ms/);
  assert.match(source, /body\[data-login-skin="forest"\]\[data-logo-intro="play"\] \.matter-login-options \{[\s\S]*animation-delay: 2780ms/);
  assert.match(source, /body\[data-login-skin="forest"\]\[data-logo-intro="play"\] \.login-actions \{[\s\S]*animation-delay: 2780ms/);
  assert.doesNotMatch(source, /translate\(30vw, -36\.5vh\)/);
  assert.match(source, /document\.body\.dataset\.logoIntro = "complete"/);
  assert.match(source, /--motion-press:\s*70ms/);
  assert.match(source, /--motion-hover:\s*110ms/);
  assert.match(source, /--motion-menu:\s*150ms/);
  assert.match(source, /--motion-content:\s*180ms/);
  assert.match(source, /--motion-panel:\s*240ms/);
  assert.match(source, /--ease-standard:\s*cubic-bezier\(0\.2, 0, 0\.38, 0\.9\)/);
  assert.match(source, /button:active/);
  assert.match(source, /button:focus-visible/);
  assert.match(source, /authPanelIn var\(--motion-content\) var\(--ease-out\) both/);
  assert.match(source, /prefers-reduced-motion: reduce/);
  assert.match(source, /transform: none !important/);
  assert.match(source, /logoIntroMotionQuery\?\.matches/);
  assert.match(source, /body:not\(\[data-login-skin="forest"\]\)\[data-logo-intro="play"\] \.brand-lockup/);
  assert.doesNotMatch(source, /logo-handoff-active/);
  assert.doesNotMatch(source, /logoDockToHeader/);
  assert.doesNotMatch(source, /appShellAfterLogoHandoff/);
  assert.match(source, /data-reset-new-password/);
  assert.match(source, /data-reset-confirm-password/);
  assert.match(source, /data-reset-confirm-submit/);
  assert.match(source, /data-resend-password-reset/);
  assert.match(source, /data-return-to-signin/);
  assert.doesNotMatch(source, /data-reset-token(?!-note)/);
  assert.doesNotMatch(source, /data-open-reset-confirm/);
  assert.doesNotMatch(source, /코드/);
  assert.doesNotMatch(source, /skipNextLoginHandoffAnimation/);
  assert.doesNotMatch(source, /const handoffDelay = skipAnimation \? 0 : 1360/);
  assert.match(source, /web\/index\.html\?desktop=1&view=home&data=live&ctx=allow&splash=0/);
  assert.match(source, /function desktopApiBaseUrlForHandoff/);
  assert.match(source, /desktop_api_base_url/);
  assert.match(source, /\["127\.0\.0\.1", "localhost"\]\.includes\(url\.hostname\)/);
  assert.match(source, /productUiTarget\(session, \{ splash: false \}\)/);
  assert.match(source, /const session = await api\.status\(\);[\s\S]*renderSession\(session\);[\s\S]*handoffToProductUi\(session\);/);
  assert.match(source, /window\.setTimeout\(\(\) => \{[\s\S]*window\.location\.assign\(target\);[\s\S]*\}, 0\);/);
  assert.match(source, /function loginFailureMessage/);
  assert.match(source, /function resetFailureMessage/);
  assert.match(source, /function isResetTokenTerminalFailure/);
  assert.match(source, /email_password_required/);
  assert.match(source, /password_reset_required/);
  assert.match(source, /auth_required/);
  assert.match(source, /AUTH_PASSWORD_TOO_SHORT/);
  assert.match(source, /AUTH_PASSWORD_RESET_TOKEN_USED/);
  assert.match(source, /AUTH_PASSWORD_RESET_TOKEN_EXPIRED/);
  assert.match(source, /최신 재설정 메일의 비밀번호 설정 버튼을 다시 열어 주세요/);
  assert.match(source, /받은편지함의 가장 최신 재설정 메일을 다시 여세요/);
  assert.match(source, /비밀번호 설정 서버에 연결하지 못했습니다/);
  assert.match(source, /현재 앱과 서버의 비밀번호 설정 경로가 맞지 않습니다/);
  assert.match(source, /비밀번호는 12자 이상이어야 합니다/);
  assert.doesNotMatch(source, /비밀번호는 8자 이상/);
  assert.match(source, /이메일 또는 비밀번호가 맞지 않습니다/);
  assert.match(source, /event\.key !== "Enter"/);
  assert.match(source, /nodes\.loginButton\?\.addEventListener/);
  assert.match(source, /\[nodes\.loginEmailInput, nodes\.loginPasswordInput\]\.filter\(Boolean\)\.forEach/);
  assert.match(source, /if \(!target\?\.input\) return/);
  assert.match(source, /nodes\.signinHelpButton\?\.addEventListener/);
  assert.match(source, /nodes\.dashboardCheckButton\?\.addEventListener/);
  assert.match(source, /onPasswordResetDeepLink/);
  assert.match(source, /비밀번호가 설정되었습니다\. 새 비밀번호로 로그인하세요\./);
  assert.match(source, /등록 여부와 관계없이 같은 안내를 보여드립니다\./);
  assert.doesNotMatch(source, /data-account-select|재설정 토큰/);
  assert.match(source, /matter_vault_admin/);
  assert.match(source, /워크스페이스 연결됨/);
  assert.match(source, /font-family: "Pretendard Matter", "SUITE Matter", sans-serif/);
  assert.match(source, /--forest-accent:\s*#26c260/);
  assert.match(source, /--am-text:\s*#15191f/);
  assert.match(source, /grid-template-columns:\s*minmax\(520px, 52fr\) minmax\(420px, 48fr\)/);
  assert.match(source, /\.auth-forest-panel[\s\S]*height:\s*100%/);
  assert.match(source, /Log in to matter/);
  assert.match(source, /Don't have a matter account yet\?/);
  assert.match(source, /가입 미리보기/);
  assert.match(source, /<span>Email<\/span>/);
  assert.match(source, /<span>Password<\/span>/);
  assert.doesNotMatch(source, /placeholder="jdoe@matter\.local"/);
  assert.doesNotMatch(source, /placeholder="••••••••••••"/);
  assert.match(source, /data-login-remember/);
  assert.match(source, /Remember me/);
  assert.match(source, /matter-login-forgot/);
  assert.match(source, /Forgot<br \/>password\?/);
  assert.match(source, /matter-login-submit/);
  assert.doesNotMatch(source, /로그인에 문제가 있나요\?/);
  assert.doesNotMatch(source, /비밀번호를 잊으셨나요\?/);
  assert.doesNotMatch(source, /계정이 없나요\?/);
  assert.doesNotMatch(source, /Can't sign in/);
  assert.match(source, /기능 확인/);
  assert.doesNotMatch(source, /AWS temporary runtime connected|Function smoke|Dashboard smoke|Admin smoke|Runtime unavailable/);
  assert.doesNotMatch(source, /MATTER_VAULT_R4_OPERATOR_TOKEN/);
  assert.doesNotMatch(source, /operatorToken/);
  assert.doesNotMatch(source, /latestResetEmail/);
  assert.doesNotMatch(source, /reset_url|email_message|reset_token\s*[:=]/);
  assert.doesNotMatch(source, /localStorage|sessionStorage|indexedDB/);
});

test("archived matter login design stays separate from the forest runtime login", async () => {
  const archived = await readFile(new URL("../src/renderer/offline.matter.html", import.meta.url), "utf8");

  assert.match(archived, /<body data-logo-intro="pending">/);
  assert.match(archived, /display:\s*flex;[\s\S]*align-items:\s*center;[\s\S]*justify-content:\s*center;/);
  assert.match(archived, /width:\s*min\(580px, 100%\)/);
  assert.match(archived, /background:\s*var\(--reference-blue\)/);
  assert.match(archived, /data-login-email/);
  assert.match(archived, /data-login-password/);
  assert.match(archived, /data-matter-login/);
  assert.match(archived, /\.\.\/\.\.\/build\/icon\.png/);
  assert.doesNotMatch(archived, /icon-source-mark\.png/);
  assert.doesNotMatch(archived, /data-login-skin="forest"/);
  assert.doesNotMatch(archived, /auth-forest-panel/);
  assert.doesNotMatch(archived, /forest-login\.jpg/);
});

test("desktop web renderer uses restrained SaaS motion tokens", async () => {
  const source = await readFile(new URL("../../web/src/motion.css", import.meta.url), "utf8");
  const entrypoint = await readFile(new URL("../../web/src/main.jsx", import.meta.url), "utf8");

  assert.match(entrypoint, /import "\.\/motion\.css"/);
  assert.match(source, /--ui-press:\s*70ms/);
  assert.match(source, /--ui-hover:\s*110ms/);
  assert.match(source, /--ui-menu:\s*150ms/);
  assert.match(source, /--ui-content:\s*180ms/);
  assert.match(source, /--ui-panel:\s*240ms/);
  assert.match(source, /--ui-pulse:\s*900ms/);
  assert.match(source, /--ease-standard:\s*cubic-bezier\(0\.2, 0, 0\.38, 0\.9\)/);
  assert.match(source, /button:active:not\(:disabled\)/);
  assert.match(source, /\.top-axis-item,\s*\.sidebar-item\s*\{[\s\S]*var\(--ui-menu\)/);
  assert.doesNotMatch(source, /\.sidebar-subnav|\.sidebar-chevron/);
  assert.match(source, /\.surface,[\s\S]*\.builder-surface[\s\S]*animation: ui-content-in var\(--ui-content\) var\(--ease-out\) both/);
  assert.match(source, /\.live-data-loading[\s\S]*animation: ui-state-pulse var\(--ui-pulse\) var\(--ease-standard\) infinite alternate/);
  assert.match(source, /@media \(prefers-reduced-motion: reduce\)[\s\S]*transition-duration: 1ms !important/);
  assert.match(source, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.live-data-loading/);
});
