function deepFreeze(value) {
  if (value && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
  }
  return value;
}

export const MIGRATION_PLATFORM_CP756_PACK_BINDING = deepFreeze({
  pack_id: "CP00-756",
  planned_pack_id: "CP00-756",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P00.M00.S01",
  last_unit_id: "RP25.P01.M02.S08",
  range: "RP25.P00.M00.S01-RP25.P01.M02.S08",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-755",
  next_pack_id: "CP00-757",
  next_subphase_id: "RP25.P01.M02.S09",
  production_ready_flag: "migration_platform_scope_contract_foundation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP757_PACK_BINDING = deepFreeze({
  pack_id: "CP00-757",
  planned_pack_id: "CP00-757",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P01.M02.S09",
  last_unit_id: "RP25.P01.M04.S06",
  range: "RP25.P01.M02.S09-RP25.P01.M04.S06",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-756",
  next_pack_id: "CP00-758",
  next_subphase_id: "RP25.P01.M04.S07",
  production_ready_flag: "migration_platform_domain_implementation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP758_PACK_BINDING = deepFreeze({
  pack_id: "CP00-758",
  planned_pack_id: "CP00-758",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P01.M04.S07",
  last_unit_id: "RP25.P01.M06.S04",
  range: "RP25.P01.M04.S07-RP25.P01.M06.S04",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-757",
  next_pack_id: "CP00-759",
  next_subphase_id: "RP25.P01.M06.S05",
  production_ready_flag: "migration_platform_permission_fixture_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP759_PACK_BINDING = deepFreeze({
  pack_id: "CP00-759",
  planned_pack_id: "CP00-759",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P01.M06.S05",
  last_unit_id: "RP25.P02.M02.S22",
  range: "RP25.P01.M06.S05-RP25.P02.M02.S22",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-758",
  next_pack_id: "CP00-760",
  next_subphase_id: "RP25.P02.M03.S01",
  production_ready_flag: "migration_platform_service_foundation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP760_PACK_BINDING = deepFreeze({
  pack_id: "CP00-760",
  planned_pack_id: "CP00-760",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P02.M03.S01",
  last_unit_id: "RP25.P02.M04.S10",
  range: "RP25.P02.M03.S01-RP25.P02.M04.S10",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-759",
  next_pack_id: "CP00-761",
  next_subphase_id: "RP25.P02.M04.S11",
  production_ready_flag: "migration_platform_primary_service_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP761_PACK_BINDING = deepFreeze({
  pack_id: "CP00-761",
  planned_pack_id: "CP00-761",
  risk_class: "A",
  unit_count: 10,
  first_unit_id: "RP25.P02.M04.S11",
  last_unit_id: "RP25.P02.M04.S20",
  range: "RP25.P02.M04.S11-RP25.P02.M04.S20",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-760",
  next_pack_id: "CP00-762",
  next_subphase_id: "RP25.P02.M04.S21",
  production_ready_flag: "migration_platform_secondary_service_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP762_PACK_BINDING = deepFreeze({
  pack_id: "CP00-762",
  planned_pack_id: "CP00-762",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P02.M04.S21",
  last_unit_id: "RP25.P02.M05.S30",
  range: "RP25.P02.M04.S21-RP25.P02.M05.S30",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-761",
  next_pack_id: "CP00-763",
  next_subphase_id: "RP25.P02.M06.S01",
  production_ready_flag: "migration_platform_permission_audit_service_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP763_PACK_BINDING = deepFreeze({
  pack_id: "CP00-763",
  planned_pack_id: "CP00-763",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P02.M06.S01",
  last_unit_id: "RP25.P03.M02.S14",
  range: "RP25.P02.M06.S01-RP25.P03.M02.S14",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-762",
  next_pack_id: "CP00-764",
  next_subphase_id: "RP25.P03.M02.S15",
  production_ready_flag: "migration_platform_fixture_interface_foundation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP764_PACK_BINDING = deepFreeze({
  pack_id: "CP00-764",
  planned_pack_id: "CP00-764",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P03.M02.S15",
  last_unit_id: "RP25.P03.M04.S12",
  range: "RP25.P03.M02.S15-RP25.P03.M04.S12",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-763",
  next_pack_id: "CP00-765",
  next_subphase_id: "RP25.P03.M04.S13",
  production_ready_flag: "migration_platform_interface_implementation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP765_PACK_BINDING = deepFreeze({
  pack_id: "CP00-765",
  planned_pack_id: "CP00-765",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P03.M04.S13",
  last_unit_id: "RP25.P03.M06.S10",
  range: "RP25.P03.M04.S13-RP25.P03.M06.S10",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-764",
  next_pack_id: "CP00-766",
  next_subphase_id: "RP25.P03.M06.S11",
  production_ready_flag: "migration_platform_interface_permission_fixture_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP766_PACK_BINDING = deepFreeze({
  pack_id: "CP00-766",
  planned_pack_id: "CP00-766",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P03.M06.S11",
  last_unit_id: "RP25.P04.M03.S18",
  range: "RP25.P03.M06.S11-RP25.P04.M03.S18",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-765",
  next_pack_id: "CP00-767",
  next_subphase_id: "RP25.P04.M03.S19",
  production_ready_flag: "migration_platform_interface_ui_foundation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP767_PACK_BINDING = deepFreeze({
  pack_id: "CP00-767",
  planned_pack_id: "CP00-767",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P04.M03.S19",
  last_unit_id: "RP25.P04.M05.S14",
  range: "RP25.P04.M03.S19-RP25.P04.M05.S14",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-766",
  next_pack_id: "CP00-768",
  next_subphase_id: "RP25.P04.M05.S15",
  production_ready_flag: "migration_platform_ui_workflow_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP768_PACK_BINDING = deepFreeze({
  pack_id: "CP00-768",
  planned_pack_id: "CP00-768",
  risk_class: "A",
  unit_count: 10,
  first_unit_id: "RP25.P04.M05.S15",
  last_unit_id: "RP25.P04.M06.S02",
  range: "RP25.P04.M05.S15-RP25.P04.M06.S02",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-767",
  next_pack_id: "CP00-769",
  next_subphase_id: "RP25.P04.M06.S03",
  production_ready_flag: "migration_platform_ui_permission_fixture_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP769_PACK_BINDING = deepFreeze({
  pack_id: "CP00-769",
  planned_pack_id: "CP00-769",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P04.M06.S03",
  last_unit_id: "RP25.P05.M02.S14",
  range: "RP25.P04.M06.S03-RP25.P05.M02.S14",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-768",
  next_pack_id: "CP00-770",
  next_subphase_id: "RP25.P05.M02.S15",
  production_ready_flag: "migration_platform_ui_fixture_foundation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP770_PACK_BINDING = deepFreeze({
  pack_id: "CP00-770",
  planned_pack_id: "CP00-770",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P05.M02.S15",
  last_unit_id: "RP25.P05.M04.S12",
  range: "RP25.P05.M02.S15-RP25.P05.M04.S12",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-769",
  next_pack_id: "CP00-771",
  next_subphase_id: "RP25.P05.M04.S13",
  production_ready_flag: "migration_platform_fixture_implementation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP771_PACK_BINDING = deepFreeze({
  pack_id: "CP00-771",
  planned_pack_id: "CP00-771",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P05.M04.S13",
  last_unit_id: "RP25.P05.M06.S08",
  range: "RP25.P05.M04.S13-RP25.P05.M06.S08",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-770",
  next_pack_id: "CP00-772",
  next_subphase_id: "RP25.P05.M06.S09",
  production_ready_flag: "migration_platform_fixture_permission_audit_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP772_PACK_BINDING = deepFreeze({
  pack_id: "CP00-772",
  planned_pack_id: "CP00-772",
  risk_class: "A",
  unit_count: 10,
  first_unit_id: "RP25.P05.M06.S09",
  last_unit_id: "RP25.P05.M06.S18",
  range: "RP25.P05.M06.S09-RP25.P05.M06.S18",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-771",
  next_pack_id: "CP00-773",
  next_subphase_id: "RP25.P05.M06.S19",
  production_ready_flag: "migration_platform_synthetic_fixture_tail_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP773_PACK_BINDING = deepFreeze({
  pack_id: "CP00-773",
  planned_pack_id: "CP00-773",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P05.M06.S19",
  last_unit_id: "RP25.P06.M02.S20",
  range: "RP25.P05.M06.S19-RP25.P06.M02.S20",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-772",
  next_pack_id: "CP00-774",
  next_subphase_id: "RP25.P06.M02.S21",
  production_ready_flag: "migration_platform_fixture_evidence_ui_foundation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP774_PACK_BINDING = deepFreeze({
  pack_id: "CP00-774",
  planned_pack_id: "CP00-774",
  risk_class: "A",
  unit_count: 10,
  first_unit_id: "RP25.P06.M02.S21",
  last_unit_id: "RP25.P06.M03.S08",
  range: "RP25.P06.M02.S21-RP25.P06.M03.S08",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-773",
  next_pack_id: "CP00-775",
  next_subphase_id: "RP25.P06.M03.S09",
  production_ready_flag: "migration_platform_permission_matrix_primary_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP775_PACK_BINDING = deepFreeze({
  pack_id: "CP00-775",
  planned_pack_id: "CP00-775",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P06.M03.S09",
  last_unit_id: "RP25.P06.M04.S18",
  range: "RP25.P06.M03.S09-RP25.P06.M04.S18",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-774",
  next_pack_id: "CP00-776",
  next_subphase_id: "RP25.P06.M04.S19",
  production_ready_flag: "migration_platform_permission_matrix_workflow_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP776_PACK_BINDING = deepFreeze({
  pack_id: "CP00-776",
  planned_pack_id: "CP00-776",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P06.M04.S19",
  last_unit_id: "RP25.P06.M05.S28",
  range: "RP25.P06.M04.S19-RP25.P06.M05.S28",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-775",
  next_pack_id: "CP00-777",
  next_subphase_id: "RP25.P06.M05.S29",
  production_ready_flag: "migration_platform_permission_matrix_audit_binding_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP777_PACK_BINDING = deepFreeze({
  pack_id: "CP00-777",
  planned_pack_id: "CP00-777",
  risk_class: "A",
  unit_count: 10,
  first_unit_id: "RP25.P06.M05.S29",
  last_unit_id: "RP25.P06.M06.S08",
  range: "RP25.P06.M05.S29-RP25.P06.M06.S08",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-776",
  next_pack_id: "CP00-778",
  next_subphase_id: "RP25.P06.M06.S09",
  production_ready_flag: "migration_platform_permission_matrix_fixture_foundation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP778_PACK_BINDING = deepFreeze({
  pack_id: "CP00-778",
  planned_pack_id: "CP00-778",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P06.M06.S09",
  last_unit_id: "RP25.P07.M02.S02",
  range: "RP25.P06.M06.S09-RP25.P07.M02.S02",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-777",
  next_pack_id: "CP00-779",
  next_subphase_id: "RP25.P07.M02.S03",
  production_ready_flag: "migration_platform_permission_fixture_failure_foundation_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP779_PACK_BINDING = deepFreeze({
  pack_id: "CP00-779",
  planned_pack_id: "CP00-779",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P07.M02.S03",
  last_unit_id: "RP25.P07.M03.S20",
  range: "RP25.P07.M02.S03-RP25.P07.M03.S20",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-778",
  next_pack_id: "CP00-780",
  next_subphase_id: "RP25.P07.M03.S21",
  production_ready_flag: "migration_platform_failure_recovery_primary_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP780_PACK_BINDING = deepFreeze({
  pack_id: "CP00-780",
  planned_pack_id: "CP00-780",
  risk_class: "B",
  unit_count: 40,
  first_unit_id: "RP25.P07.M03.S21",
  last_unit_id: "RP25.P07.M04.S30",
  range: "RP25.P07.M03.S21-RP25.P07.M04.S30",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-779",
  next_pack_id: "CP00-781",
  next_subphase_id: "RP25.P07.M05.S01",
  production_ready_flag: "migration_platform_failure_recovery_workflow_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP781_PACK_BINDING = deepFreeze({
  pack_id: "CP00-781",
  planned_pack_id: "CP00-781",
  risk_class: "A",
  unit_count: 10,
  first_unit_id: "RP25.P07.M05.S01",
  last_unit_id: "RP25.P07.M05.S10",
  range: "RP25.P07.M05.S01-RP25.P07.M05.S10",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-780",
  next_pack_id: "CP00-782",
  next_subphase_id: "RP25.P07.M05.S11",
  production_ready_flag: "migration_platform_failure_recovery_audit_binding_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP782_PACK_BINDING = deepFreeze({
  pack_id: "CP00-782",
  planned_pack_id: "CP00-782",
  risk_class: "A",
  unit_count: 10,
  first_unit_id: "RP25.P07.M05.S11",
  last_unit_id: "RP25.P07.M05.S20",
  range: "RP25.P07.M05.S11-RP25.P07.M05.S20",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-781",
  next_pack_id: "CP00-783",
  next_subphase_id: "RP25.P07.M05.S21",
  production_ready_flag: "migration_platform_failure_recovery_audit_tail_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP783_PACK_BINDING = deepFreeze({
  pack_id: "CP00-783",
  planned_pack_id: "CP00-783",
  risk_class: "A",
  unit_count: 10,
  first_unit_id: "RP25.P07.M05.S21",
  last_unit_id: "RP25.P07.M05.S30",
  range: "RP25.P07.M05.S21-RP25.P07.M05.S30",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-782",
  next_pack_id: "CP00-784",
  next_subphase_id: "RP25.P07.M06.S01",
  production_ready_flag: "migration_platform_failure_recovery_audit_closeout_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP784_PACK_BINDING = deepFreeze({
  pack_id: "CP00-784",
  planned_pack_id: "CP00-784",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P07.M06.S01",
  last_unit_id: "RP25.P08.M02.S04",
  range: "RP25.P07.M06.S01-RP25.P08.M02.S04",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-783",
  next_pack_id: "CP00-785",
  next_subphase_id: "RP25.P08.M02.S05",
  production_ready_flag: "migration_platform_failure_fixture_review_bridge_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP785_PACK_BINDING = deepFreeze({
  pack_id: "CP00-785",
  planned_pack_id: "CP00-785",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P08.M02.S05",
  last_unit_id: "RP25.P08.M09.S02",
  range: "RP25.P08.M02.S05-RP25.P08.M09.S02",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-784",
  next_pack_id: "CP00-786",
  next_subphase_id: "RP25.P08.M09.S03",
  production_ready_flag: "migration_platform_review_receipt_implementation_bridge_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP786_PACK_BINDING = deepFreeze({
  pack_id: "CP00-786",
  planned_pack_id: "CP00-786",
  risk_class: "C",
  unit_count: 150,
  first_unit_id: "RP25.P08.M09.S03",
  last_unit_id: "RP25.P09.M06.S06",
  range: "RP25.P08.M09.S03-RP25.P09.M06.S06",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-785",
  next_pack_id: "CP00-787",
  next_subphase_id: "RP25.P09.M06.S07",
  production_ready_flag: "migration_platform_review_packet_risk_bridge_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_CP787_PACK_BINDING = deepFreeze({
  pack_id: "CP00-787",
  planned_pack_id: "CP00-787",
  risk_class: "C",
  unit_count: 86,
  first_unit_id: "RP25.P09.M06.S07",
  last_unit_id: "RP25.P09.M10.S10",
  range: "RP25.P09.M06.S07-RP25.P09.M10.S10",
  plan_ref: "docs/closeout-pack-plan/closeout-pack-plan.json",
  upstream_pack_id: "CP00-786",
  next_pack_id: "CP00-788",
  next_subphase_id: "RP26.P00.M00.S01",
  production_ready_flag: "migration_platform_review_risk_closeout_descriptor_verified",
  hermes_gate: "H25",
  claude_gate: "C25",
});

export const MIGRATION_PLATFORM_PROGRAM_CONTRACT = deepFreeze({
  program_id: "RP25",
  program_title: "Migration Platform",
  program_scope: "file server, SharePoint, Drive, iManage import",
  package_name: "migration",
  contract_ref: "contracts/migration-platform-contract.json",
  upstream_program_id: "RP24",
  upstream_scope: "Korean Legal Depth",
  downstream_program_id: "RP26",
  hermes_gate: "H25",
  claude_gate: "C25",
  entities: ["MigrationSource", "MigrationBatch", "ImportPlan", "MappingRule", "DryRunReport", "ImportReceipt"],
});

export const MIGRATION_PLATFORM_NO_WRITE_ATTESTATION = deepFreeze({
  descriptor_only: true,
  no_real_data: true,
  synthetic_only: true,
  writes_product_state: false,
  creates_database_rows: false,
  updates_database_rows: false,
  writes_object_storage: false,
  external_runtime_called: false,
  file_server_runtime_opened: false,
  sharepoint_runtime_opened: false,
  google_drive_runtime_opened: false,
  imanage_runtime_opened: false,
  import_runtime_opened: false,
});

const BASELINE_ROWS = deepFreeze([
  "Scope inventory",
  "Acceptance gate definition",
  "Non-goal boundary",
]);

const CONTRACT_TYPE_ROWS = deepFreeze([
  ...BASELINE_ROWS,
  "Target file map",
  "Contract schema outline",
  "Ownership note",
  "Matter-first trace note",
  "Permission baseline note",
  "Audit baseline note",
  "Synthetic data policy",
]);

const CONTRACT_RUNTIME_ROWS = deepFreeze([
  ...CONTRACT_TYPE_ROWS,
  "Risk register row",
  "Blocked-claim rule",
  "Hermes preflight fields",
  "Claude review prompts",
  "Human approval note",
  "Closeout handoff",
  "Dependency list",
  "Downstream RP routing",
  "Command matrix",
  "Receipt shape",
]);

const DOMAIN_MODEL_ROWS = deepFreeze([
  "Package directory layout",
  "Primary entity identifier",
  "Tenant scope field",
  "Matter trace reference",
  "Lifecycle status enum",
  "Ownership metadata",
  "Reference relationship map",
  "Required field registry",
  "Optional field registry",
  "State transition map",
  "Validation helper",
  "Fixture model",
  "Serialization shape",
  "Public export",
  "Model unit test",
  "Invalid reference test",
  "Ownership drift test",
  "Hermes model summary",
  "Claude model review prompt",
  "Closeout handoff",
]);

const IMPLEMENTATION_SLICE_ROWS = deepFreeze([
  ...DOMAIN_MODEL_ROWS,
  "Documentation entry",
  "Index export check",
]);

const SERVICE_ROWS = deepFreeze([
  "Service entrypoint contract",
  "Request normalization",
  "Tenant boundary precheck",
  "Matter trace precheck",
  "Permission precheck",
  "Audit hint precheck",
  "Primary happy path",
  "Secondary workflow path",
  "State transition enforcement",
  "Idempotency key handling",
  "Lock acquisition rule",
  "Persistence boundary",
  "Validation error mapping",
  "Review-required routing",
  "Approval-required routing",
  "Blocked-claim output",
  "Rollback behavior",
  "Retry behavior",
  "Unit test: happy path",
  "Unit test: denied path",
]);

const SERVICE_EXTENDED_ROWS = deepFreeze([
  ...SERVICE_ROWS,
  "Unit test: review path",
  "Integration smoke case",
]);

const SERVICE_REVIEW_ROWS = deepFreeze([
  ...SERVICE_EXTENDED_ROWS,
  "Golden fixture binding",
  "Hermes service evidence",
  "Claude service review prompt",
  "Human approval summary",
  "Closeout handoff",
  "Performance note",
  "Observability note",
  "Future extension point",
]);

const INTERFACE_ROWS = deepFreeze([
  "Public export map",
  "Request contract",
  "Response contract",
  "Error code taxonomy",
  "Permission annotation",
  "Audit annotation",
  "Pagination or filtering contract",
  "Serialization guard",
  "Unauthorized data omission",
  "API fixture",
  "Contract test",
  "Invalid request test",
  "Denied response test",
  "Hermes API evidence",
  "Claude interface prompt",
  "Documentation example",
  "Versioning note",
  "Closeout handoff",
  "Downstream consumer note",
  "Command rerun",
  "Schema drift check",
  "Backward compatibility check",
]);

const UI_SURFACE_ROWS = deepFreeze([
  "UI surface inventory",
  "Data dependency map",
  "Loading state",
  "Empty state",
  "Denied state",
  "Review-required state",
  "Primary interaction",
  "Secondary interaction",
  "Permission badge",
  "Audit hint display",
  "Error message copy",
  "Responsive desktop layout",
  "Responsive mobile layout",
  "Keyboard/focus behavior",
  "Visual density check",
  "Synthetic fixture binding",
  "Build smoke",
  "Hermes UI evidence",
  "Claude UI leak prompt",
  "Closeout handoff",
  "State snapshot",
  "No unauthorized count leak",
]);

const FIXTURE_ROWS = deepFreeze([
  "Base tenant fixture",
  "Base user fixture",
  "Base matter fixture",
  "Base document fixture",
  "Primary golden case",
  "Secondary golden case",
  "Review-required case",
  "Denied case",
  "Cross-tenant case",
  "Missing context case",
  "Audit hint case",
  "Security trimming case",
  "AI retrieval or analytics case",
  "Fixture manifest",
  "Golden test",
  "Failure test",
  "Hermes fixture evidence",
  "Claude missing-test prompt",
  "Closeout handoff",
  "No-real-data check",
  "Stable ID check",
  "Replay command",
]);

const PERMISSION_MATRIX_ROWS = deepFreeze([
  "Permission matrix row",
  "View decision binding",
  "Search decision binding",
  "Mutation decision binding",
  "Export/download decision binding",
  "Share decision binding",
  "AI retrieval decision binding",
  "Audit hint fields",
  "Matched rule capture",
  "Deny-over-allow check",
  "Legal hold interaction",
  "Ethical wall interaction",
  "Object ACL interaction",
  "Review-required route",
  "Approval-required route",
  "Security trimming proof",
  "Audit event expectation",
  "Permission fixture",
  "Allowed test",
  "Denied test",
]);

const PERMISSION_MATRIX_TEST_ROWS = deepFreeze([
  "Cross-tenant test",
  "Leak prevention test",
]);

const PERMISSION_MATRIX_CLOSEOUT_ROWS = deepFreeze([
  "Hermes security evidence",
  "Claude bypass prompt",
  "Human approval note",
  "Closeout handoff",
  "Downstream audit note",
  "No-real-data check",
  "Command rerun",
  "Risk register update",
]);

const PERMISSION_MATRIX_FAILURE_ROWS = deepFreeze([
  "Failure taxonomy",
  "Missing tenant failure",
  "Missing actor failure",
  "Missing Matter failure",
  "Missing resource failure",
  "Unknown action failure",
  "Cross-tenant failure",
  "Permission denied failure",
  "Ambiguous rule failure",
  "Stale reference failure",
  "Lock conflict failure",
  "Retry exhaustion failure",
  "Rollback expectation",
  "Compensation expectation",
  "Blocked-claim receipt",
  "Failure fixture",
  "Failure unit test",
  "Failure integration smoke",
  "Audit failure hint",
  "Hermes failure evidence",
]);

const PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS = deepFreeze([
  "Claude edge-case prompt",
  "Human escalation note",
  "Closeout handoff",
  "No silent success check",
  "No data leak check",
  "Recovery documentation",
  "Command rerun",
  "Risk register update",
  "Downstream correction route",
  "Future incident note",
]);

const REVIEW_RECEIPT_ROWS = deepFreeze([
  "Hermes command matrix",
  "Evidence field list",
  "Changed-file receipt",
  "Command result receipt",
  "Fixture summary receipt",
  "Blocked-claim receipt",
  "Permission summary receipt",
  "Audit summary receipt",
  "No-real-data receipt",
  "Claude dependency marker",
  "Human approval marker",
  "PASS semantics",
  "PASS_WITH_FINDINGS semantics",
  "BLOCK semantics",
  "Evidence template",
  "Validation command check",
  "Harness boundary note",
  "Closeout handoff",
  "Regression receipt",
  "Next gate readiness",
]);

const REVIEW_RECEIPT_EXTENDED_ROWS = deepFreeze([
  ...REVIEW_RECEIPT_ROWS,
  "Documentation update",
  "Operator summary",
]);

const CLAUDE_REVIEW_RISK_ROWS = deepFreeze([
  "Architecture review questions",
  "Security review questions",
  "Permission bypass questions",
  "Audit completeness questions",
  "Missing test questions",
  "UI leak questions",
  "Downstream readiness questions",
  "Risk register",
  "Severity taxonomy",
  "Go/no-go verdict format",
  "Finding routing map",
  "Human approval summary",
  "Claude review packet",
  "Closeout criteria",
  "PASS closeout note",
  "PASS_WITH_FINDINGS closeout note",
  "BLOCK closeout note",
  "Next RP dependency",
  "Documentation update",
  "Command rerun",
]);

const CLAUDE_REVIEW_RISK_EXTENDED_ROWS = deepFreeze([
  ...CLAUDE_REVIEW_RISK_ROWS,
  "Review receipt placeholder",
  "Future correction slot",
]);

export const MIGRATION_PLATFORM_CP756_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 108,
    contract: 8,
    security_audit: 16,
    hermes_evidence: 7,
    claude_review: 3,
    ui: 8,
  },
  phase_counts: {
    "RP25.P00": 122,
    "RP25.P01": 28,
  },
  micro_phase_row_counts: {
    "RP25.P00.M00": 3,
    "RP25.P00.M01": 3,
    "RP25.P00.M02": 10,
    "RP25.P00.M03": 20,
    "RP25.P00.M04": 13,
    "RP25.P00.M05": 20,
    "RP25.P00.M06": 10,
    "RP25.P00.M07": 20,
    "RP25.P00.M08": 10,
    "RP25.P00.M09": 10,
    "RP25.P00.M10": 3,
    "RP25.P01.M00": 10,
    "RP25.P01.M01": 10,
    "RP25.P01.M02": 8,
  },
  micro_title_row_counts: {
    "Scope Inventory": 13,
    "Contract Draft": 13,
    "Type And Shape Definition": 18,
    "Primary Implementation Slice": 20,
    "Secondary Workflow Slice": 13,
    "Permission And Audit Binding": 20,
    "Synthetic Fixture Set": 10,
    "Test And Golden Case Set": 20,
    "Hermes Evidence Packet": 10,
    "Claude Review Packet": 10,
    "Closeout And Next Handoff": 3,
  },
  required_section_rows: {
    "RP25.P00.M00": BASELINE_ROWS,
    "RP25.P00.M01": BASELINE_ROWS,
    "RP25.P00.M02": CONTRACT_TYPE_ROWS,
    "RP25.P00.M03": CONTRACT_RUNTIME_ROWS,
    "RP25.P00.M04": CONTRACT_RUNTIME_ROWS.slice(0, 13),
    "RP25.P00.M05": CONTRACT_RUNTIME_ROWS,
    "RP25.P00.M06": CONTRACT_TYPE_ROWS,
    "RP25.P00.M07": CONTRACT_RUNTIME_ROWS,
    "RP25.P00.M08": CONTRACT_TYPE_ROWS,
    "RP25.P00.M09": CONTRACT_TYPE_ROWS,
    "RP25.P00.M10": BASELINE_ROWS,
    "RP25.P01.M00": DOMAIN_MODEL_ROWS.slice(0, 10),
    "RP25.P01.M01": DOMAIN_MODEL_ROWS.slice(0, 10),
    "RP25.P01.M02": DOMAIN_MODEL_ROWS.slice(0, 8),
  },
  required_section_micro_titles: {
    "RP25.P00.M00": "Scope Inventory",
    "RP25.P00.M01": "Contract Draft",
    "RP25.P00.M02": "Type And Shape Definition",
    "RP25.P00.M03": "Primary Implementation Slice",
    "RP25.P00.M04": "Secondary Workflow Slice",
    "RP25.P00.M05": "Permission And Audit Binding",
    "RP25.P00.M06": "Synthetic Fixture Set",
    "RP25.P00.M07": "Test And Golden Case Set",
    "RP25.P00.M08": "Hermes Evidence Packet",
    "RP25.P00.M09": "Claude Review Packet",
    "RP25.P00.M10": "Closeout And Next Handoff",
    "RP25.P01.M00": "Scope Inventory",
    "RP25.P01.M01": "Contract Draft",
    "RP25.P01.M02": "Type And Shape Definition",
  },
  required_no_leak_guards: [
    "descriptor_only",
    "no_real_client_or_matter_data",
    "no_external_credentials",
    "no_source_system_runtime_connection",
    "no_import_runtime_execution",
    "no_unverified_knowledge_creation",
    "no_product_state_write",
    "claude_read_only_non_final",
  ],
  allowed_claude_tools: ["Read", "Grep", "Glob"],
  forbidden_review_evidence: [
    "not_logged_in",
    "malformed_json",
    "usage_limit",
    "tool_call_shaped_output",
    "zero_byte_stdout",
    "fenced_json_with_prose",
  ],
  required_public_exports: [
    "MIGRATION_PLATFORM_CP756_PACK_BINDING",
    "MIGRATION_PLATFORM_CP756_REQUIREMENTS",
    "createMigrationPlatformCp756ScopeContractFoundationCaseSet",
    "createMigrationPlatformCp756ScopeContractFoundationDescriptor",
    "validateMigrationPlatformCp756ScopeContractFoundationCoverage",
    "validateMigrationPlatformCp756ScopeContractFoundationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP757_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 23,
    ui: 5,
    fixture: 2,
    test: 6,
    hermes_evidence: 2,
    claude_review: 2,
  },
  phase_counts: {
    "RP25.P01": 40,
  },
  micro_phase_row_counts: {
    "RP25.P01.M02": 12,
    "RP25.P01.M03": 22,
    "RP25.P01.M04": 6,
  },
  micro_title_row_counts: {
    "Type And Shape Definition": 12,
    "Primary Implementation Slice": 22,
    "Secondary Workflow Slice": 6,
  },
  required_section_rows: {
    "RP25.P01.M02": DOMAIN_MODEL_ROWS.slice(8, 20),
    "RP25.P01.M03": IMPLEMENTATION_SLICE_ROWS,
    "RP25.P01.M04": DOMAIN_MODEL_ROWS.slice(0, 6),
  },
  required_section_micro_titles: {
    "RP25.P01.M02": "Type And Shape Definition",
    "RP25.P01.M03": "Primary Implementation Slice",
    "RP25.P01.M04": "Secondary Workflow Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP757_PACK_BINDING",
    "MIGRATION_PLATFORM_CP757_REQUIREMENTS",
    "createMigrationPlatformCp757DomainImplementationCaseSet",
    "createMigrationPlatformCp757DomainImplementationDescriptor",
    "validateMigrationPlatformCp757DomainImplementationCoverage",
    "validateMigrationPlatformCp757DomainImplementationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP758_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 22,
    ui: 6,
    fixture: 2,
    test: 6,
    hermes_evidence: 2,
    claude_review: 2,
  },
  phase_counts: {
    "RP25.P01": 40,
  },
  micro_phase_row_counts: {
    "RP25.P01.M04": 14,
    "RP25.P01.M05": 22,
    "RP25.P01.M06": 4,
  },
  micro_title_row_counts: {
    "Secondary Workflow Slice": 14,
    "Permission And Audit Binding": 22,
    "Synthetic Fixture Set": 4,
  },
  required_section_rows: {
    "RP25.P01.M04": DOMAIN_MODEL_ROWS.slice(6, 20),
    "RP25.P01.M05": IMPLEMENTATION_SLICE_ROWS,
    "RP25.P01.M06": DOMAIN_MODEL_ROWS.slice(0, 4),
  },
  required_section_micro_titles: {
    "RP25.P01.M04": "Secondary Workflow Slice",
    "RP25.P01.M05": "Permission And Audit Binding",
    "RP25.P01.M06": "Synthetic Fixture Set",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP758_PACK_BINDING",
    "MIGRATION_PLATFORM_CP758_REQUIREMENTS",
    "createMigrationPlatformCp758PermissionFixtureCaseSet",
    "createMigrationPlatformCp758PermissionFixtureDescriptor",
    "validateMigrationPlatformCp758PermissionFixtureCoverage",
    "validateMigrationPlatformCp758PermissionFixtureDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP759_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 77,
    ui: 23,
    fixture: 4,
    test: 20,
    hermes_evidence: 4,
    claude_review: 7,
    contract: 3,
    security_audit: 6,
    failure_recovery: 6,
  },
  phase_counts: {
    "RP25.P01": 88,
    "RP25.P02": 62,
  },
  micro_phase_row_counts: {
    "RP25.P01.M06": 16,
    "RP25.P01.M07": 22,
    "RP25.P01.M08": 20,
    "RP25.P01.M09": 20,
    "RP25.P01.M10": 10,
    "RP25.P02.M00": 20,
    "RP25.P02.M01": 20,
    "RP25.P02.M02": 22,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 16,
    "Test And Golden Case Set": 22,
    "Hermes Evidence Packet": 20,
    "Claude Review Packet": 20,
    "Closeout And Next Handoff": 10,
    "Scope Inventory": 20,
    "Contract Draft": 20,
    "Type And Shape Definition": 22,
  },
  required_section_rows: {
    "RP25.P01.M06": DOMAIN_MODEL_ROWS.slice(4, 20),
    "RP25.P01.M07": IMPLEMENTATION_SLICE_ROWS,
    "RP25.P01.M08": DOMAIN_MODEL_ROWS,
    "RP25.P01.M09": DOMAIN_MODEL_ROWS,
    "RP25.P01.M10": DOMAIN_MODEL_ROWS.slice(0, 10),
    "RP25.P02.M00": SERVICE_ROWS,
    "RP25.P02.M01": SERVICE_ROWS,
    "RP25.P02.M02": SERVICE_EXTENDED_ROWS,
  },
  required_section_micro_titles: {
    "RP25.P01.M06": "Synthetic Fixture Set",
    "RP25.P01.M07": "Test And Golden Case Set",
    "RP25.P01.M08": "Hermes Evidence Packet",
    "RP25.P01.M09": "Claude Review Packet",
    "RP25.P01.M10": "Closeout And Next Handoff",
    "RP25.P02.M00": "Scope Inventory",
    "RP25.P02.M01": "Contract Draft",
    "RP25.P02.M02": "Type And Shape Definition",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP759_PACK_BINDING",
    "MIGRATION_PLATFORM_CP759_REQUIREMENTS",
    "createMigrationPlatformCp759ServiceFoundationCaseSet",
    "createMigrationPlatformCp759ServiceFoundationDescriptor",
    "validateMigrationPlatformCp759ServiceFoundationCoverage",
    "validateMigrationPlatformCp759ServiceFoundationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP760_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    contract: 2,
    implementation: 20,
    security_audit: 4,
    ui: 4,
    claude_review: 2,
    failure_recovery: 2,
    test: 4,
    fixture: 1,
    hermes_evidence: 1,
  },
  phase_counts: {
    "RP25.P02": 40,
  },
  micro_phase_row_counts: {
    "RP25.P02.M03": 30,
    "RP25.P02.M04": 10,
  },
  micro_title_row_counts: {
    "Primary Implementation Slice": 30,
    "Secondary Workflow Slice": 10,
  },
  required_section_rows: {
    "RP25.P02.M03": SERVICE_REVIEW_ROWS,
    "RP25.P02.M04": SERVICE_ROWS.slice(0, 10),
  },
  required_section_micro_titles: {
    "RP25.P02.M03": "Primary Implementation Slice",
    "RP25.P02.M04": "Secondary Workflow Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP760_PACK_BINDING",
    "MIGRATION_PLATFORM_CP760_REQUIREMENTS",
    "createMigrationPlatformCp760PrimaryServiceCaseSet",
    "createMigrationPlatformCp760PrimaryServiceDescriptor",
    "validateMigrationPlatformCp760PrimaryServiceCoverage",
    "validateMigrationPlatformCp760PrimaryServiceDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP761_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    ui: 2,
    implementation: 3,
    claude_review: 1,
    failure_recovery: 2,
    test: 2,
  },
  phase_counts: {
    "RP25.P02": 10,
  },
  micro_phase_row_counts: {
    "RP25.P02.M04": 10,
  },
  micro_title_row_counts: {
    "Secondary Workflow Slice": 10,
  },
  required_section_rows: {
    "RP25.P02.M04": SERVICE_ROWS.slice(10, 20),
  },
  required_section_micro_titles: {
    "RP25.P02.M04": "Secondary Workflow Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP761_PACK_BINDING",
    "MIGRATION_PLATFORM_CP761_REQUIREMENTS",
    "createMigrationPlatformCp761SecondaryServiceCaseSet",
    "createMigrationPlatformCp761SecondaryServiceDescriptor",
    "validateMigrationPlatformCp761SecondaryServiceCoverage",
    "validateMigrationPlatformCp761SecondaryServiceDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP762_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    test: 6,
    fixture: 2,
    hermes_evidence: 2,
    claude_review: 3,
    implementation: 19,
    contract: 1,
    security_audit: 2,
    ui: 3,
    failure_recovery: 2,
  },
  phase_counts: {
    "RP25.P02": 40,
  },
  micro_phase_row_counts: {
    "RP25.P02.M04": 10,
    "RP25.P02.M05": 30,
  },
  micro_title_row_counts: {
    "Secondary Workflow Slice": 10,
    "Permission And Audit Binding": 30,
  },
  required_section_rows: {
    "RP25.P02.M04": SERVICE_REVIEW_ROWS.slice(20, 30),
    "RP25.P02.M05": SERVICE_REVIEW_ROWS,
  },
  required_section_micro_titles: {
    "RP25.P02.M04": "Secondary Workflow Slice",
    "RP25.P02.M05": "Permission And Audit Binding",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP762_PACK_BINDING",
    "MIGRATION_PLATFORM_CP762_REQUIREMENTS",
    "createMigrationPlatformCp762PermissionAuditServiceCaseSet",
    "createMigrationPlatformCp762PermissionAuditServiceDescriptor",
    "validateMigrationPlatformCp762PermissionAuditServiceCoverage",
    "validateMigrationPlatformCp762PermissionAuditServiceDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP763_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    contract: 17,
    implementation: 62,
    security_audit: 16,
    ui: 15,
    claude_review: 6,
    failure_recovery: 10,
    test: 21,
    fixture: 1,
    hermes_evidence: 2,
  },
  phase_counts: {
    "RP25.P02": 116,
    "RP25.P03": 34,
  },
  micro_phase_row_counts: {
    "RP25.P02.M06": 22,
    "RP25.P02.M07": 30,
    "RP25.P02.M08": 22,
    "RP25.P02.M09": 22,
    "RP25.P02.M10": 20,
    "RP25.P03.M00": 10,
    "RP25.P03.M01": 10,
    "RP25.P03.M02": 14,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 22,
    "Test And Golden Case Set": 30,
    "Hermes Evidence Packet": 22,
    "Claude Review Packet": 22,
    "Closeout And Next Handoff": 20,
    "Scope Inventory": 10,
    "Contract Draft": 10,
    "Type And Shape Definition": 14,
  },
  required_section_rows: {
    "RP25.P02.M06": SERVICE_EXTENDED_ROWS,
    "RP25.P02.M07": SERVICE_REVIEW_ROWS,
    "RP25.P02.M08": SERVICE_EXTENDED_ROWS,
    "RP25.P02.M09": SERVICE_EXTENDED_ROWS,
    "RP25.P02.M10": SERVICE_ROWS,
    "RP25.P03.M00": INTERFACE_ROWS.slice(0, 10),
    "RP25.P03.M01": INTERFACE_ROWS.slice(0, 10),
    "RP25.P03.M02": INTERFACE_ROWS.slice(0, 14),
  },
  required_section_micro_titles: {
    "RP25.P02.M06": "Synthetic Fixture Set",
    "RP25.P02.M07": "Test And Golden Case Set",
    "RP25.P02.M08": "Hermes Evidence Packet",
    "RP25.P02.M09": "Claude Review Packet",
    "RP25.P02.M10": "Closeout And Next Handoff",
    "RP25.P03.M00": "Scope Inventory",
    "RP25.P03.M01": "Contract Draft",
    "RP25.P03.M02": "Type And Shape Definition",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP763_PACK_BINDING",
    "MIGRATION_PLATFORM_CP763_REQUIREMENTS",
    "createMigrationPlatformCp763FixtureInterfaceFoundationCaseSet",
    "createMigrationPlatformCp763FixtureInterfaceFoundationDescriptor",
    "validateMigrationPlatformCp763FixtureInterfaceFoundationCoverage",
    "validateMigrationPlatformCp763FixtureInterfaceFoundationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP764_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    claude_review: 2,
    implementation: 19,
    contract: 9,
    security_audit: 4,
    test: 5,
    hermes_evidence: 1,
  },
  phase_counts: {
    "RP25.P03": 40,
  },
  micro_phase_row_counts: {
    "RP25.P03.M02": 6,
    "RP25.P03.M03": 22,
    "RP25.P03.M04": 12,
  },
  micro_title_row_counts: {
    "Type And Shape Definition": 6,
    "Primary Implementation Slice": 22,
    "Secondary Workflow Slice": 12,
  },
  required_section_rows: {
    "RP25.P03.M02": INTERFACE_ROWS.slice(14, 20),
    "RP25.P03.M03": INTERFACE_ROWS,
    "RP25.P03.M04": INTERFACE_ROWS.slice(0, 12),
  },
  required_section_micro_titles: {
    "RP25.P03.M02": "Type And Shape Definition",
    "RP25.P03.M03": "Primary Implementation Slice",
    "RP25.P03.M04": "Secondary Workflow Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP764_PACK_BINDING",
    "MIGRATION_PLATFORM_CP764_REQUIREMENTS",
    "createMigrationPlatformCp764InterfaceImplementationCaseSet",
    "createMigrationPlatformCp764InterfaceImplementationDescriptor",
    "validateMigrationPlatformCp764InterfaceImplementationCoverage",
    "validateMigrationPlatformCp764InterfaceImplementationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP765_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    test: 4,
    hermes_evidence: 2,
    claude_review: 2,
    implementation: 19,
    contract: 9,
    security_audit: 4,
  },
  phase_counts: {
    "RP25.P03": 40,
  },
  micro_phase_row_counts: {
    "RP25.P03.M04": 8,
    "RP25.P03.M05": 22,
    "RP25.P03.M06": 10,
  },
  micro_title_row_counts: {
    "Secondary Workflow Slice": 8,
    "Permission And Audit Binding": 22,
    "Synthetic Fixture Set": 10,
  },
  required_section_rows: {
    "RP25.P03.M04": INTERFACE_ROWS.slice(12, 20),
    "RP25.P03.M05": INTERFACE_ROWS,
    "RP25.P03.M06": INTERFACE_ROWS.slice(0, 10),
  },
  required_section_micro_titles: {
    "RP25.P03.M04": "Secondary Workflow Slice",
    "RP25.P03.M05": "Permission And Audit Binding",
    "RP25.P03.M06": "Synthetic Fixture Set",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP765_PACK_BINDING",
    "MIGRATION_PLATFORM_CP765_REQUIREMENTS",
    "createMigrationPlatformCp765InterfacePermissionFixtureCaseSet",
    "createMigrationPlatformCp765InterfacePermissionFixtureDescriptor",
    "validateMigrationPlatformCp765InterfacePermissionFixtureCoverage",
    "validateMigrationPlatformCp765InterfacePermissionFixtureDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP766_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    test: 15,
    hermes_evidence: 7,
    claude_review: 10,
    implementation: 52,
    contract: 17,
    security_audit: 16,
    ui: 30,
    fixture: 3,
  },
  phase_counts: {
    "RP25.P03": 82,
    "RP25.P04": 68,
  },
  micro_phase_row_counts: {
    "RP25.P03.M06": 10,
    "RP25.P03.M07": 22,
    "RP25.P03.M08": 20,
    "RP25.P03.M09": 20,
    "RP25.P03.M10": 10,
    "RP25.P04.M00": 10,
    "RP25.P04.M01": 20,
    "RP25.P04.M02": 20,
    "RP25.P04.M03": 18,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 10,
    "Test And Golden Case Set": 22,
    "Hermes Evidence Packet": 20,
    "Claude Review Packet": 20,
    "Closeout And Next Handoff": 10,
    "Scope Inventory": 10,
    "Contract Draft": 20,
    "Type And Shape Definition": 20,
    "Primary Implementation Slice": 18,
  },
  required_section_rows: {
    "RP25.P03.M06": INTERFACE_ROWS.slice(10, 20),
    "RP25.P03.M07": INTERFACE_ROWS,
    "RP25.P03.M08": INTERFACE_ROWS.slice(0, 20),
    "RP25.P03.M09": INTERFACE_ROWS.slice(0, 20),
    "RP25.P03.M10": INTERFACE_ROWS.slice(0, 10),
    "RP25.P04.M00": UI_SURFACE_ROWS.slice(0, 10),
    "RP25.P04.M01": UI_SURFACE_ROWS.slice(0, 20),
    "RP25.P04.M02": UI_SURFACE_ROWS.slice(0, 20),
    "RP25.P04.M03": UI_SURFACE_ROWS.slice(0, 18),
  },
  required_section_micro_titles: {
    "RP25.P03.M06": "Synthetic Fixture Set",
    "RP25.P03.M07": "Test And Golden Case Set",
    "RP25.P03.M08": "Hermes Evidence Packet",
    "RP25.P03.M09": "Claude Review Packet",
    "RP25.P03.M10": "Closeout And Next Handoff",
    "RP25.P04.M00": "Scope Inventory",
    "RP25.P04.M01": "Contract Draft",
    "RP25.P04.M02": "Type And Shape Definition",
    "RP25.P04.M03": "Primary Implementation Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP766_PACK_BINDING",
    "MIGRATION_PLATFORM_CP766_REQUIREMENTS",
    "createMigrationPlatformCp766InterfaceUiFoundationCaseSet",
    "createMigrationPlatformCp766InterfaceUiFoundationDescriptor",
    "validateMigrationPlatformCp766InterfaceUiFoundationCoverage",
    "validateMigrationPlatformCp766InterfaceUiFoundationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP767_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    claude_review: 4,
    implementation: 11,
    ui: 18,
    security_audit: 4,
    fixture: 1,
    test: 1,
    hermes_evidence: 1,
  },
  phase_counts: {
    "RP25.P04": 40,
  },
  micro_phase_row_counts: {
    "RP25.P04.M03": 4,
    "RP25.P04.M04": 22,
    "RP25.P04.M05": 14,
  },
  micro_title_row_counts: {
    "Primary Implementation Slice": 4,
    "Secondary Workflow Slice": 22,
    "Permission And Audit Binding": 14,
  },
  required_section_rows: {
    "RP25.P04.M03": UI_SURFACE_ROWS.slice(18, 22),
    "RP25.P04.M04": UI_SURFACE_ROWS,
    "RP25.P04.M05": UI_SURFACE_ROWS.slice(0, 14),
  },
  required_section_micro_titles: {
    "RP25.P04.M03": "Primary Implementation Slice",
    "RP25.P04.M04": "Secondary Workflow Slice",
    "RP25.P04.M05": "Permission And Audit Binding",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP767_PACK_BINDING",
    "MIGRATION_PLATFORM_CP767_REQUIREMENTS",
    "createMigrationPlatformCp767UiWorkflowCaseSet",
    "createMigrationPlatformCp767UiWorkflowDescriptor",
    "validateMigrationPlatformCp767UiWorkflowCoverage",
    "validateMigrationPlatformCp767UiWorkflowDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP768_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 4,
    fixture: 1,
    test: 1,
    hermes_evidence: 1,
    claude_review: 1,
    ui: 2,
  },
  phase_counts: {
    "RP25.P04": 10,
  },
  micro_phase_row_counts: {
    "RP25.P04.M05": 8,
    "RP25.P04.M06": 2,
  },
  micro_title_row_counts: {
    "Permission And Audit Binding": 8,
    "Synthetic Fixture Set": 2,
  },
  required_section_rows: {
    "RP25.P04.M05": UI_SURFACE_ROWS.slice(14, 22),
    "RP25.P04.M06": UI_SURFACE_ROWS.slice(0, 2),
  },
  required_section_micro_titles: {
    "RP25.P04.M05": "Permission And Audit Binding",
    "RP25.P04.M06": "Synthetic Fixture Set",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP768_PACK_BINDING",
    "MIGRATION_PLATFORM_CP768_REQUIREMENTS",
    "createMigrationPlatformCp768UiPermissionFixtureCaseSet",
    "createMigrationPlatformCp768UiPermissionFixtureDescriptor",
    "validateMigrationPlatformCp768UiPermissionFixtureCoverage",
    "validateMigrationPlatformCp768UiPermissionFixtureDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP769_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    ui: 43,
    claude_review: 13,
    security_audit: 14,
    implementation: 41,
    fixture: 25,
    test: 8,
    hermes_evidence: 6,
  },
  phase_counts: {
    "RP25.P04": 106,
    "RP25.P05": 44,
  },
  micro_phase_row_counts: {
    "RP25.P04.M06": 20,
    "RP25.P04.M07": 22,
    "RP25.P04.M08": 22,
    "RP25.P04.M09": 22,
    "RP25.P04.M10": 20,
    "RP25.P05.M00": 10,
    "RP25.P05.M01": 20,
    "RP25.P05.M02": 14,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 20,
    "Test And Golden Case Set": 22,
    "Hermes Evidence Packet": 22,
    "Claude Review Packet": 22,
    "Closeout And Next Handoff": 20,
    "Scope Inventory": 10,
    "Contract Draft": 20,
    "Type And Shape Definition": 14,
  },
  required_section_rows: {
    "RP25.P04.M06": UI_SURFACE_ROWS.slice(2, 22),
    "RP25.P04.M07": UI_SURFACE_ROWS,
    "RP25.P04.M08": UI_SURFACE_ROWS,
    "RP25.P04.M09": UI_SURFACE_ROWS,
    "RP25.P04.M10": UI_SURFACE_ROWS.slice(0, 20),
    "RP25.P05.M00": FIXTURE_ROWS.slice(0, 10),
    "RP25.P05.M01": FIXTURE_ROWS.slice(0, 20),
    "RP25.P05.M02": FIXTURE_ROWS.slice(0, 14),
  },
  required_section_micro_titles: {
    "RP25.P04.M06": "Synthetic Fixture Set",
    "RP25.P04.M07": "Test And Golden Case Set",
    "RP25.P04.M08": "Hermes Evidence Packet",
    "RP25.P04.M09": "Claude Review Packet",
    "RP25.P04.M10": "Closeout And Next Handoff",
    "RP25.P05.M00": "Scope Inventory",
    "RP25.P05.M01": "Contract Draft",
    "RP25.P05.M02": "Type And Shape Definition",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP769_PACK_BINDING",
    "MIGRATION_PLATFORM_CP769_REQUIREMENTS",
    "createMigrationPlatformCp769UiFixtureFoundationCaseSet",
    "createMigrationPlatformCp769UiFixtureFoundationDescriptor",
    "validateMigrationPlatformCp769UiFixtureFoundationCoverage",
    "validateMigrationPlatformCp769UiFixtureFoundationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP770_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    test: 6,
    hermes_evidence: 2,
    implementation: 13,
    fixture: 13,
    claude_review: 2,
    security_audit: 4,
  },
  phase_counts: {
    "RP25.P05": 40,
  },
  micro_phase_row_counts: {
    "RP25.P05.M02": 6,
    "RP25.P05.M03": 22,
    "RP25.P05.M04": 12,
  },
  micro_title_row_counts: {
    "Type And Shape Definition": 6,
    "Primary Implementation Slice": 22,
    "Secondary Workflow Slice": 12,
  },
  required_section_rows: {
    "RP25.P05.M02": FIXTURE_ROWS.slice(14, 20),
    "RP25.P05.M03": FIXTURE_ROWS,
    "RP25.P05.M04": FIXTURE_ROWS.slice(0, 12),
  },
  required_section_micro_titles: {
    "RP25.P05.M02": "Type And Shape Definition",
    "RP25.P05.M03": "Primary Implementation Slice",
    "RP25.P05.M04": "Secondary Workflow Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP770_PACK_BINDING",
    "MIGRATION_PLATFORM_CP770_REQUIREMENTS",
    "createMigrationPlatformCp770FixtureImplementationCaseSet",
    "createMigrationPlatformCp770FixtureImplementationDescriptor",
    "validateMigrationPlatformCp770FixtureImplementationCoverage",
    "validateMigrationPlatformCp770FixtureImplementationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP771_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 14,
    fixture: 14,
    test: 6,
    hermes_evidence: 2,
    claude_review: 2,
    security_audit: 2,
  },
  phase_counts: {
    "RP25.P05": 40,
  },
  micro_phase_row_counts: {
    "RP25.P05.M04": 10,
    "RP25.P05.M05": 22,
    "RP25.P05.M06": 8,
  },
  micro_title_row_counts: {
    "Secondary Workflow Slice": 10,
    "Permission And Audit Binding": 22,
    "Synthetic Fixture Set": 8,
  },
  required_section_rows: {
    "RP25.P05.M04": FIXTURE_ROWS.slice(12, 22),
    "RP25.P05.M05": FIXTURE_ROWS,
    "RP25.P05.M06": FIXTURE_ROWS.slice(0, 8),
  },
  required_section_micro_titles: {
    "RP25.P05.M04": "Secondary Workflow Slice",
    "RP25.P05.M05": "Permission And Audit Binding",
    "RP25.P05.M06": "Synthetic Fixture Set",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP771_PACK_BINDING",
    "MIGRATION_PLATFORM_CP771_REQUIREMENTS",
    "createMigrationPlatformCp771FixturePermissionAuditCaseSet",
    "createMigrationPlatformCp771FixturePermissionAuditDescriptor",
    "validateMigrationPlatformCp771FixturePermissionAuditCoverage",
    "validateMigrationPlatformCp771FixturePermissionAuditDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP772_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 3,
    security_audit: 2,
    fixture: 1,
    test: 3,
    hermes_evidence: 1,
  },
  phase_counts: {
    "RP25.P05": 10,
  },
  micro_phase_row_counts: {
    "RP25.P05.M06": 10,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 10,
  },
  required_section_rows: {
    "RP25.P05.M06": FIXTURE_ROWS.slice(8, 18),
  },
  required_section_micro_titles: {
    "RP25.P05.M06": "Synthetic Fixture Set",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP772_PACK_BINDING",
    "MIGRATION_PLATFORM_CP772_REQUIREMENTS",
    "createMigrationPlatformCp772SyntheticFixtureTailCaseSet",
    "createMigrationPlatformCp772SyntheticFixtureTailDescriptor",
    "validateMigrationPlatformCp772SyntheticFixtureTailCoverage",
    "validateMigrationPlatformCp772SyntheticFixtureTailDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP773_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 58,
    fixture: 28,
    claude_review: 7,
    security_audit: 23,
    test: 18,
    hermes_evidence: 4,
    ui: 12,
  },
  phase_counts: {
    "RP25.P05": 90,
    "RP25.P06": 60,
  },
  micro_phase_row_counts: {
    "RP25.P05.M06": 4,
    "RP25.P05.M07": 22,
    "RP25.P05.M08": 22,
    "RP25.P05.M09": 22,
    "RP25.P05.M10": 20,
    "RP25.P06.M00": 20,
    "RP25.P06.M01": 20,
    "RP25.P06.M02": 20,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 4,
    "Test And Golden Case Set": 22,
    "Hermes Evidence Packet": 22,
    "Claude Review Packet": 22,
    "Closeout And Next Handoff": 20,
    "Scope Inventory": 20,
    "Contract Draft": 20,
    "Type And Shape Definition": 20,
  },
  required_section_rows: {
    "RP25.P05.M06": FIXTURE_ROWS.slice(18, 22),
    "RP25.P05.M07": FIXTURE_ROWS,
    "RP25.P05.M08": FIXTURE_ROWS,
    "RP25.P05.M09": FIXTURE_ROWS,
    "RP25.P05.M10": FIXTURE_ROWS.slice(0, 20),
    "RP25.P06.M00": PERMISSION_MATRIX_ROWS,
    "RP25.P06.M01": PERMISSION_MATRIX_ROWS,
    "RP25.P06.M02": PERMISSION_MATRIX_ROWS,
  },
  required_section_micro_titles: {
    "RP25.P05.M06": "Synthetic Fixture Set",
    "RP25.P05.M07": "Test And Golden Case Set",
    "RP25.P05.M08": "Hermes Evidence Packet",
    "RP25.P05.M09": "Claude Review Packet",
    "RP25.P05.M10": "Closeout And Next Handoff",
    "RP25.P06.M00": "Scope Inventory",
    "RP25.P06.M01": "Contract Draft",
    "RP25.P06.M02": "Type And Shape Definition",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP773_PACK_BINDING",
    "MIGRATION_PLATFORM_CP773_REQUIREMENTS",
    "createMigrationPlatformCp773FixtureEvidenceUiFoundationCaseSet",
    "createMigrationPlatformCp773FixtureEvidenceUiFoundationDescriptor",
    "validateMigrationPlatformCp773FixtureEvidenceUiFoundationCoverage",
    "validateMigrationPlatformCp773FixtureEvidenceUiFoundationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP774_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    test: 2,
    security_audit: 2,
    implementation: 6,
  },
  phase_counts: {
    "RP25.P06": 10,
  },
  micro_phase_row_counts: {
    "RP25.P06.M02": 2,
    "RP25.P06.M03": 8,
  },
  micro_title_row_counts: {
    "Type And Shape Definition": 2,
    "Primary Implementation Slice": 8,
  },
  required_section_rows: {
    "RP25.P06.M02": PERMISSION_MATRIX_TEST_ROWS,
    "RP25.P06.M03": PERMISSION_MATRIX_ROWS.slice(0, 8),
  },
  required_section_micro_titles: {
    "RP25.P06.M02": "Type And Shape Definition",
    "RP25.P06.M03": "Primary Implementation Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP774_PACK_BINDING",
    "MIGRATION_PLATFORM_CP774_REQUIREMENTS",
    "createMigrationPlatformCp774PermissionMatrixPrimaryCaseSet",
    "createMigrationPlatformCp774PermissionMatrixPrimaryDescriptor",
    "validateMigrationPlatformCp774PermissionMatrixPrimaryCoverage",
    "validateMigrationPlatformCp774PermissionMatrixPrimaryDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP775_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 15,
    ui: 8,
    claude_review: 3,
    security_audit: 9,
    test: 4,
    hermes_evidence: 1,
  },
  phase_counts: {
    "RP25.P06": 40,
  },
  micro_phase_row_counts: {
    "RP25.P06.M03": 22,
    "RP25.P06.M04": 18,
  },
  micro_title_row_counts: {
    "Primary Implementation Slice": 22,
    "Secondary Workflow Slice": 18,
  },
  required_section_rows: {
    "RP25.P06.M03": [
      ...PERMISSION_MATRIX_ROWS.slice(8, 20),
      ...PERMISSION_MATRIX_TEST_ROWS,
      ...PERMISSION_MATRIX_CLOSEOUT_ROWS,
    ],
    "RP25.P06.M04": PERMISSION_MATRIX_ROWS.slice(0, 18),
  },
  required_section_micro_titles: {
    "RP25.P06.M03": "Primary Implementation Slice",
    "RP25.P06.M04": "Secondary Workflow Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP775_PACK_BINDING",
    "MIGRATION_PLATFORM_CP775_REQUIREMENTS",
    "createMigrationPlatformCp775PermissionMatrixWorkflowCaseSet",
    "createMigrationPlatformCp775PermissionMatrixWorkflowDescriptor",
    "validateMigrationPlatformCp775PermissionMatrixWorkflowCoverage",
    "validateMigrationPlatformCp775PermissionMatrixWorkflowDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP776_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    test: 8,
    hermes_evidence: 2,
    claude_review: 3,
    implementation: 16,
    security_audit: 7,
    ui: 4,
  },
  phase_counts: {
    "RP25.P06": 40,
  },
  micro_phase_row_counts: {
    "RP25.P06.M04": 12,
    "RP25.P06.M05": 28,
  },
  micro_title_row_counts: {
    "Secondary Workflow Slice": 12,
    "Permission And Audit Binding": 28,
  },
  required_section_rows: {
    "RP25.P06.M04": [
      ...PERMISSION_MATRIX_ROWS.slice(18, 20),
      ...PERMISSION_MATRIX_TEST_ROWS,
      ...PERMISSION_MATRIX_CLOSEOUT_ROWS,
    ],
    "RP25.P06.M05": [
      ...PERMISSION_MATRIX_ROWS,
      ...PERMISSION_MATRIX_TEST_ROWS,
      ...PERMISSION_MATRIX_CLOSEOUT_ROWS.slice(0, 6),
    ],
  },
  required_section_micro_titles: {
    "RP25.P06.M04": "Secondary Workflow Slice",
    "RP25.P06.M05": "Permission And Audit Binding",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP776_PACK_BINDING",
    "MIGRATION_PLATFORM_CP776_REQUIREMENTS",
    "createMigrationPlatformCp776PermissionMatrixAuditBindingCaseSet",
    "createMigrationPlatformCp776PermissionMatrixAuditBindingDescriptor",
    "validateMigrationPlatformCp776PermissionMatrixAuditBindingCoverage",
    "validateMigrationPlatformCp776PermissionMatrixAuditBindingDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP777_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 8,
    security_audit: 2,
  },
  phase_counts: {
    "RP25.P06": 10,
  },
  micro_phase_row_counts: {
    "RP25.P06.M05": 2,
    "RP25.P06.M06": 8,
  },
  micro_title_row_counts: {
    "Permission And Audit Binding": 2,
    "Synthetic Fixture Set": 8,
  },
  required_section_rows: {
    "RP25.P06.M05": PERMISSION_MATRIX_CLOSEOUT_ROWS.slice(6, 8),
    "RP25.P06.M06": PERMISSION_MATRIX_ROWS.slice(0, 8),
  },
  required_section_micro_titles: {
    "RP25.P06.M05": "Permission And Audit Binding",
    "RP25.P06.M06": "Synthetic Fixture Set",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP777_PACK_BINDING",
    "MIGRATION_PLATFORM_CP777_REQUIREMENTS",
    "createMigrationPlatformCp777PermissionMatrixFixtureFoundationCaseSet",
    "createMigrationPlatformCp777PermissionMatrixFixtureFoundationDescriptor",
    "validateMigrationPlatformCp777PermissionMatrixFixtureFoundationCoverage",
    "validateMigrationPlatformCp777PermissionMatrixFixtureFoundationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP778_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 41,
    ui: 20,
    claude_review: 6,
    security_audit: 28,
    test: 22,
    hermes_evidence: 5,
    failure_recovery: 26,
    fixture: 2,
  },
  phase_counts: {
    "RP25.P06": 108,
    "RP25.P07": 42,
  },
  micro_phase_row_counts: {
    "RP25.P06.M06": 14,
    "RP25.P06.M07": 30,
    "RP25.P06.M08": 22,
    "RP25.P06.M09": 22,
    "RP25.P06.M10": 20,
    "RP25.P07.M00": 20,
    "RP25.P07.M01": 20,
    "RP25.P07.M02": 2,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 14,
    "Test And Golden Case Set": 30,
    "Hermes Evidence Packet": 22,
    "Claude Review Packet": 22,
    "Closeout And Next Handoff": 20,
    "Scope Inventory": 20,
    "Contract Draft": 20,
    "Type And Shape Definition": 2,
  },
  required_section_rows: {
    "RP25.P06.M06": [
      ...PERMISSION_MATRIX_ROWS.slice(8, 20),
      ...PERMISSION_MATRIX_TEST_ROWS,
    ],
    "RP25.P06.M07": [
      ...PERMISSION_MATRIX_ROWS,
      ...PERMISSION_MATRIX_TEST_ROWS,
      ...PERMISSION_MATRIX_CLOSEOUT_ROWS,
    ],
    "RP25.P06.M08": [
      ...PERMISSION_MATRIX_ROWS,
      ...PERMISSION_MATRIX_TEST_ROWS,
    ],
    "RP25.P06.M09": [
      ...PERMISSION_MATRIX_ROWS,
      ...PERMISSION_MATRIX_TEST_ROWS,
    ],
    "RP25.P06.M10": PERMISSION_MATRIX_ROWS,
    "RP25.P07.M00": PERMISSION_MATRIX_FAILURE_ROWS,
    "RP25.P07.M01": PERMISSION_MATRIX_FAILURE_ROWS,
    "RP25.P07.M02": PERMISSION_MATRIX_FAILURE_ROWS.slice(0, 2),
  },
  required_section_micro_titles: {
    "RP25.P06.M06": "Synthetic Fixture Set",
    "RP25.P06.M07": "Test And Golden Case Set",
    "RP25.P06.M08": "Hermes Evidence Packet",
    "RP25.P06.M09": "Claude Review Packet",
    "RP25.P06.M10": "Closeout And Next Handoff",
    "RP25.P07.M00": "Scope Inventory",
    "RP25.P07.M01": "Contract Draft",
    "RP25.P07.M02": "Type And Shape Definition",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP778_PACK_BINDING",
    "MIGRATION_PLATFORM_CP778_REQUIREMENTS",
    "createMigrationPlatformCp778PermissionFixtureFailureFoundationCaseSet",
    "createMigrationPlatformCp778PermissionFixtureFailureFoundationDescriptor",
    "validateMigrationPlatformCp778PermissionFixtureFailureFoundationCoverage",
    "validateMigrationPlatformCp778PermissionFixtureFailureFoundationDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP779_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    failure_recovery: 22,
    security_audit: 4,
    implementation: 3,
    hermes_evidence: 4,
    fixture: 2,
    test: 4,
    claude_review: 1,
  },
  phase_counts: {
    "RP25.P07": 40,
  },
  micro_phase_row_counts: {
    "RP25.P07.M02": 20,
    "RP25.P07.M03": 20,
  },
  micro_title_row_counts: {
    "Type And Shape Definition": 20,
    "Primary Implementation Slice": 20,
  },
  required_section_rows: {
    "RP25.P07.M02": [
      ...PERMISSION_MATRIX_FAILURE_ROWS.slice(2),
      ...PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS.slice(0, 2),
    ],
    "RP25.P07.M03": PERMISSION_MATRIX_FAILURE_ROWS,
  },
  required_section_micro_titles: {
    "RP25.P07.M02": "Type And Shape Definition",
    "RP25.P07.M03": "Primary Implementation Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP779_PACK_BINDING",
    "MIGRATION_PLATFORM_CP779_REQUIREMENTS",
    "createMigrationPlatformCp779FailureRecoveryPrimaryCaseSet",
    "createMigrationPlatformCp779FailureRecoveryPrimaryDescriptor",
    "validateMigrationPlatformCp779FailureRecoveryPrimaryCoverage",
    "validateMigrationPlatformCp779FailureRecoveryPrimaryDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP780_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    claude_review: 2,
    implementation: 19,
    failure_recovery: 12,
    security_audit: 2,
    hermes_evidence: 2,
    fixture: 1,
    test: 2,
  },
  phase_counts: {
    "RP25.P07": 40,
  },
  micro_phase_row_counts: {
    "RP25.P07.M03": 10,
    "RP25.P07.M04": 30,
  },
  micro_title_row_counts: {
    "Primary Implementation Slice": 10,
    "Secondary Workflow Slice": 30,
  },
  required_section_rows: {
    "RP25.P07.M03": PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS,
    "RP25.P07.M04": [
      ...PERMISSION_MATRIX_FAILURE_ROWS,
      ...PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS,
    ],
  },
  required_section_micro_titles: {
    "RP25.P07.M03": "Primary Implementation Slice",
    "RP25.P07.M04": "Secondary Workflow Slice",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP780_PACK_BINDING",
    "MIGRATION_PLATFORM_CP780_REQUIREMENTS",
    "createMigrationPlatformCp780FailureRecoveryWorkflowCaseSet",
    "createMigrationPlatformCp780FailureRecoveryWorkflowDescriptor",
    "validateMigrationPlatformCp780FailureRecoveryWorkflowCoverage",
    "validateMigrationPlatformCp780FailureRecoveryWorkflowDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP781_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    failure_recovery: 9,
    security_audit: 1,
  },
  phase_counts: {
    "RP25.P07": 10,
  },
  micro_phase_row_counts: {
    "RP25.P07.M05": 10,
  },
  micro_title_row_counts: {
    "Permission And Audit Binding": 10,
  },
  required_section_rows: {
    "RP25.P07.M05": PERMISSION_MATRIX_FAILURE_ROWS.slice(0, 10),
  },
  required_section_micro_titles: {
    "RP25.P07.M05": "Permission And Audit Binding",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP781_PACK_BINDING",
    "MIGRATION_PLATFORM_CP781_REQUIREMENTS",
    "createMigrationPlatformCp781FailureRecoveryAuditBindingCaseSet",
    "createMigrationPlatformCp781FailureRecoveryAuditBindingDescriptor",
    "validateMigrationPlatformCp781FailureRecoveryAuditBindingCoverage",
    "validateMigrationPlatformCp781FailureRecoveryAuditBindingDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP782_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    failure_recovery: 3,
    implementation: 1,
    hermes_evidence: 2,
    fixture: 1,
    test: 2,
    security_audit: 1,
  },
  phase_counts: {
    "RP25.P07": 10,
  },
  micro_phase_row_counts: {
    "RP25.P07.M05": 10,
  },
  micro_title_row_counts: {
    "Permission And Audit Binding": 10,
  },
  required_section_rows: {
    "RP25.P07.M05": PERMISSION_MATRIX_FAILURE_ROWS.slice(10, 20),
  },
  required_section_micro_titles: {
    "RP25.P07.M05": "Permission And Audit Binding",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP782_PACK_BINDING",
    "MIGRATION_PLATFORM_CP782_REQUIREMENTS",
    "createMigrationPlatformCp782FailureRecoveryAuditTailCaseSet",
    "createMigrationPlatformCp782FailureRecoveryAuditTailDescriptor",
    "validateMigrationPlatformCp782FailureRecoveryAuditTailCoverage",
    "validateMigrationPlatformCp782FailureRecoveryAuditTailDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP783_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    claude_review: 1,
    implementation: 9,
  },
  phase_counts: {
    "RP25.P07": 10,
  },
  micro_phase_row_counts: {
    "RP25.P07.M05": 10,
  },
  micro_title_row_counts: {
    "Permission And Audit Binding": 10,
  },
  required_section_rows: {
    "RP25.P07.M05": PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS,
  },
  required_section_micro_titles: {
    "RP25.P07.M05": "Permission And Audit Binding",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP783_PACK_BINDING",
    "MIGRATION_PLATFORM_CP783_REQUIREMENTS",
    "createMigrationPlatformCp783FailureRecoveryAuditCloseoutCaseSet",
    "createMigrationPlatformCp783FailureRecoveryAuditCloseoutDescriptor",
    "validateMigrationPlatformCp783FailureRecoveryAuditCloseoutCoverage",
    "validateMigrationPlatformCp783FailureRecoveryAuditCloseoutDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP784_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    failure_recovery: 60,
    security_audit: 10,
    implementation: 25,
    hermes_evidence: 33,
    fixture: 5,
    test: 11,
    claude_review: 6,
  },
  phase_counts: {
    "RP25.P07": 116,
    "RP25.P08": 34,
  },
  micro_phase_row_counts: {
    "RP25.P07.M06": 22,
    "RP25.P07.M07": 30,
    "RP25.P07.M08": 22,
    "RP25.P07.M09": 22,
    "RP25.P07.M10": 20,
    "RP25.P08.M00": 10,
    "RP25.P08.M01": 20,
    "RP25.P08.M02": 4,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 22,
    "Test And Golden Case Set": 30,
    "Hermes Evidence Packet": 22,
    "Claude Review Packet": 22,
    "Closeout And Next Handoff": 20,
    "Scope Inventory": 10,
    "Contract Draft": 20,
    "Type And Shape Definition": 4,
  },
  required_section_rows: {
    "RP25.P07.M06": [
      ...PERMISSION_MATRIX_FAILURE_ROWS,
      ...PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS.slice(0, 2),
    ],
    "RP25.P07.M07": [
      ...PERMISSION_MATRIX_FAILURE_ROWS,
      ...PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS,
    ],
    "RP25.P07.M08": [
      ...PERMISSION_MATRIX_FAILURE_ROWS,
      ...PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS.slice(0, 2),
    ],
    "RP25.P07.M09": [
      ...PERMISSION_MATRIX_FAILURE_ROWS,
      ...PERMISSION_MATRIX_FAILURE_CLOSEOUT_ROWS.slice(0, 2),
    ],
    "RP25.P07.M10": PERMISSION_MATRIX_FAILURE_ROWS,
    "RP25.P08.M00": REVIEW_RECEIPT_ROWS.slice(0, 10),
    "RP25.P08.M01": REVIEW_RECEIPT_ROWS,
    "RP25.P08.M02": REVIEW_RECEIPT_ROWS.slice(0, 4),
  },
  required_section_micro_titles: {
    "RP25.P07.M06": "Synthetic Fixture Set",
    "RP25.P07.M07": "Test And Golden Case Set",
    "RP25.P07.M08": "Hermes Evidence Packet",
    "RP25.P07.M09": "Claude Review Packet",
    "RP25.P07.M10": "Closeout And Next Handoff",
    "RP25.P08.M00": "Scope Inventory",
    "RP25.P08.M01": "Contract Draft",
    "RP25.P08.M02": "Type And Shape Definition",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP784_PACK_BINDING",
    "MIGRATION_PLATFORM_CP784_REQUIREMENTS",
    "createMigrationPlatformCp784FailureFixtureReviewBridgeCaseSet",
    "createMigrationPlatformCp784FailureFixtureReviewBridgeDescriptor",
    "validateMigrationPlatformCp784FailureFixtureReviewBridgeCoverage",
    "validateMigrationPlatformCp784FailureFixtureReviewBridgeDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP785_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    hermes_evidence: 68,
    claude_review: 7,
    implementation: 68,
    test: 7,
  },
  phase_counts: {
    "RP25.P08": 150,
  },
  micro_phase_row_counts: {
    "RP25.P08.M02": 16,
    "RP25.P08.M03": 22,
    "RP25.P08.M04": 22,
    "RP25.P08.M05": 22,
    "RP25.P08.M06": 22,
    "RP25.P08.M07": 22,
    "RP25.P08.M08": 22,
    "RP25.P08.M09": 2,
  },
  micro_title_row_counts: {
    "Type And Shape Definition": 16,
    "Primary Implementation Slice": 22,
    "Secondary Workflow Slice": 22,
    "Permission And Audit Binding": 22,
    "Synthetic Fixture Set": 22,
    "Test And Golden Case Set": 22,
    "Hermes Evidence Packet": 22,
    "Claude Review Packet": 2,
  },
  required_section_rows: {
    "RP25.P08.M02": REVIEW_RECEIPT_ROWS.slice(4, 20),
    "RP25.P08.M03": REVIEW_RECEIPT_EXTENDED_ROWS,
    "RP25.P08.M04": REVIEW_RECEIPT_EXTENDED_ROWS,
    "RP25.P08.M05": REVIEW_RECEIPT_EXTENDED_ROWS,
    "RP25.P08.M06": REVIEW_RECEIPT_EXTENDED_ROWS,
    "RP25.P08.M07": REVIEW_RECEIPT_EXTENDED_ROWS,
    "RP25.P08.M08": REVIEW_RECEIPT_EXTENDED_ROWS,
    "RP25.P08.M09": REVIEW_RECEIPT_ROWS.slice(0, 2),
  },
  required_section_micro_titles: {
    "RP25.P08.M02": "Type And Shape Definition",
    "RP25.P08.M03": "Primary Implementation Slice",
    "RP25.P08.M04": "Secondary Workflow Slice",
    "RP25.P08.M05": "Permission And Audit Binding",
    "RP25.P08.M06": "Synthetic Fixture Set",
    "RP25.P08.M07": "Test And Golden Case Set",
    "RP25.P08.M08": "Hermes Evidence Packet",
    "RP25.P08.M09": "Claude Review Packet",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP785_PACK_BINDING",
    "MIGRATION_PLATFORM_CP785_REQUIREMENTS",
    "createMigrationPlatformCp785ReviewReceiptImplementationBridgeCaseSet",
    "createMigrationPlatformCp785ReviewReceiptImplementationBridgeDescriptor",
    "validateMigrationPlatformCp785ReviewReceiptImplementationBridgeCoverage",
    "validateMigrationPlatformCp785ReviewReceiptImplementationBridgeDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP786_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    hermes_evidence: 20,
    claude_review: 20,
    implementation: 80,
    test: 9,
    security_audit: 14,
    ui: 7,
  },
  phase_counts: {
    "RP25.P08": 40,
    "RP25.P09": 110,
  },
  micro_phase_row_counts: {
    "RP25.P08.M09": 20,
    "RP25.P08.M10": 20,
    "RP25.P09.M00": 10,
    "RP25.P09.M01": 10,
    "RP25.P09.M02": 20,
    "RP25.P09.M03": 22,
    "RP25.P09.M04": 20,
    "RP25.P09.M05": 22,
    "RP25.P09.M06": 6,
  },
  micro_title_row_counts: {
    "Claude Review Packet": 20,
    "Closeout And Next Handoff": 20,
    "Scope Inventory": 10,
    "Contract Draft": 10,
    "Type And Shape Definition": 20,
    "Primary Implementation Slice": 22,
    "Secondary Workflow Slice": 20,
    "Permission And Audit Binding": 22,
    "Synthetic Fixture Set": 6,
  },
  required_section_rows: {
    "RP25.P08.M09": REVIEW_RECEIPT_EXTENDED_ROWS.slice(2, 22),
    "RP25.P08.M10": REVIEW_RECEIPT_ROWS,
    "RP25.P09.M00": CLAUDE_REVIEW_RISK_ROWS.slice(0, 10),
    "RP25.P09.M01": CLAUDE_REVIEW_RISK_ROWS.slice(0, 10),
    "RP25.P09.M02": CLAUDE_REVIEW_RISK_ROWS,
    "RP25.P09.M03": CLAUDE_REVIEW_RISK_EXTENDED_ROWS,
    "RP25.P09.M04": CLAUDE_REVIEW_RISK_ROWS,
    "RP25.P09.M05": CLAUDE_REVIEW_RISK_EXTENDED_ROWS,
    "RP25.P09.M06": CLAUDE_REVIEW_RISK_ROWS.slice(0, 6),
  },
  required_section_micro_titles: {
    "RP25.P08.M09": "Claude Review Packet",
    "RP25.P08.M10": "Closeout And Next Handoff",
    "RP25.P09.M00": "Scope Inventory",
    "RP25.P09.M01": "Contract Draft",
    "RP25.P09.M02": "Type And Shape Definition",
    "RP25.P09.M03": "Primary Implementation Slice",
    "RP25.P09.M04": "Secondary Workflow Slice",
    "RP25.P09.M05": "Permission And Audit Binding",
    "RP25.P09.M06": "Synthetic Fixture Set",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP786_PACK_BINDING",
    "MIGRATION_PLATFORM_CP786_REQUIREMENTS",
    "createMigrationPlatformCp786ReviewPacketRiskBridgeCaseSet",
    "createMigrationPlatformCp786ReviewPacketRiskBridgeDescriptor",
    "validateMigrationPlatformCp786ReviewPacketRiskBridgeCoverage",
    "validateMigrationPlatformCp786ReviewPacketRiskBridgeDescriptor",
  ],
});

export const MIGRATION_PLATFORM_CP787_REQUIREMENTS = deepFreeze({
  deliverable_counts: {
    implementation: 57,
    claude_review: 12,
    security_audit: 8,
    test: 4,
    ui: 4,
    hermes_evidence: 1,
  },
  phase_counts: {
    "RP25.P09": 86,
  },
  micro_phase_row_counts: {
    "RP25.P09.M06": 14,
    "RP25.P09.M07": 22,
    "RP25.P09.M08": 20,
    "RP25.P09.M09": 20,
    "RP25.P09.M10": 10,
  },
  micro_title_row_counts: {
    "Synthetic Fixture Set": 14,
    "Test And Golden Case Set": 22,
    "Hermes Evidence Packet": 20,
    "Claude Review Packet": 20,
    "Closeout And Next Handoff": 10,
  },
  required_section_rows: {
    "RP25.P09.M06": CLAUDE_REVIEW_RISK_ROWS.slice(6, 20),
    "RP25.P09.M07": CLAUDE_REVIEW_RISK_EXTENDED_ROWS,
    "RP25.P09.M08": CLAUDE_REVIEW_RISK_ROWS,
    "RP25.P09.M09": CLAUDE_REVIEW_RISK_ROWS,
    "RP25.P09.M10": CLAUDE_REVIEW_RISK_ROWS.slice(0, 10),
  },
  required_section_micro_titles: {
    "RP25.P09.M06": "Synthetic Fixture Set",
    "RP25.P09.M07": "Test And Golden Case Set",
    "RP25.P09.M08": "Hermes Evidence Packet",
    "RP25.P09.M09": "Claude Review Packet",
    "RP25.P09.M10": "Closeout And Next Handoff",
  },
  required_no_leak_guards: MIGRATION_PLATFORM_CP756_REQUIREMENTS.required_no_leak_guards,
  allowed_claude_tools: MIGRATION_PLATFORM_CP756_REQUIREMENTS.allowed_claude_tools,
  forbidden_review_evidence: MIGRATION_PLATFORM_CP756_REQUIREMENTS.forbidden_review_evidence,
  required_public_exports: [
    "MIGRATION_PLATFORM_CP787_PACK_BINDING",
    "MIGRATION_PLATFORM_CP787_REQUIREMENTS",
    "createMigrationPlatformCp787ReviewRiskCloseoutCaseSet",
    "createMigrationPlatformCp787ReviewRiskCloseoutDescriptor",
    "validateMigrationPlatformCp787ReviewRiskCloseoutCoverage",
    "validateMigrationPlatformCp787ReviewRiskCloseoutDescriptor",
  ],
});
